/**
 * 组件表——由迁移脚本生成 + 手工治理更新（分类重划 2026-08）。
 */
import type { ComponentEntry } from './types.ts'

export const components: ComponentEntry[] = [
  {
    "id": "videoplayer",
    "name": "VideoPlayer",
    "category": "core",
    "desc": "视频播放器——原生 video 封装（controls/封面/宽高比/事件——零依赖）",
    "sourceFile": "src/components/VideoPlayer/VideoPlayer.ts",
    "cssFile": "src/components/VideoPlayer/VideoPlayer.css",
    "testFile": "src/components/VideoPlayer/VideoPlayer.test.ts"
  },
  {
    "id": "math",
    "name": "Math",
    "category": "core",
    "desc": "轻量公式渲染——自研 LaTeX 子集（上下标/分数/根号/希腊字母——零依赖不引 KaTeX）",
    "sourceFile": "src/components/Math/Math.ts",
    "cssFile": "src/components/Math/Math.css",
    "testFile": "src/components/Math/Math.test.ts"
  },
  {
    "id": "markdowneditor",
    "name": "MarkdownEditor",
    "category": "editor",
    "desc": "分屏 Markdown 编辑器——textarea + 实时预览（复用 Markdown parser 零漂移）",
    "sourceFile": "src/components/MarkdownEditor/MarkdownEditor.ts",
    "cssFile": "src/components/MarkdownEditor/MarkdownEditor.css",
    "testFile": "src/components/MarkdownEditor/MarkdownEditor.test.ts"
  },
  {
    "id": "codeeditor",
    "name": "CodeEditor",
    "category": "editor",
    "desc": "轻量代码编辑器——textarea + 行号 + Tab 缩进（零依赖，不引 Monaco）",
    "sourceFile": "src/components/CodeEditor/CodeEditor.ts",
    "cssFile": "src/components/CodeEditor/CodeEditor.css",
    "testFile": "src/components/CodeEditor/CodeEditor.test.ts"
  },
  {
    "id": "imagecropper",
    "name": "ImageCropper",
    "category": "editor",
    "desc": "图片裁剪——canvas 原生 API + 拖拽裁剪框 + 比例控制（零依赖）",
    "sourceFile": "src/components/ImageCropper/ImageCropper.ts",
    "cssFile": "src/components/ImageCropper/ImageCropper.css",
    "testFile": "src/components/ImageCropper/ImageCropper.test.ts"
  },
  {
    "id": "wave",
    "name": "Wave",
    "category": "core",
    "desc": "点击水波纹动效——包装任意可点击元素（纯 CSS，reduced-motion 自动降级）",
    "sourceFile": "src/components/Wave/Wave.ts",
    "cssFile": "src/components/Wave/Wave.css",
    "testFile": "src/components/Wave/Wave.test.ts"
  },
  {
    "id": "sortablelist",
    "name": "SortableList",
    "category": "viz",
    "desc": "拖拽排序列表——useDragDrop 原语 + keyed 身份（任务/字段/配置排序）",
    "sourceFile": "src/components/SortableList/SortableList.ts",
    "cssFile": "src/components/SortableList/SortableList.css",
    "testFile": "src/components/SortableList/SortableList.test.ts"
  },
  {
    "id": "exportcsv",
    "name": "ExportCSV",
    "category": "display",
    "desc": "数据导出 CSV——RFC 4180 转义 + BOM（Excel 兼容）零依赖",
    "sourceFile": "src/components/ExportCSV/ExportCSV.ts",
    "testFile": "src/components/ExportCSV/ExportCSV.test.ts"
  },
  {
    "id": "button",
    "name": "Button",
    "category": "core",
    "desc": "4 variants × 3 sizes + loading + block + disabled",
    "codeKey": "button",
    "demo": "DemoButton",
    "sourceFile": "src/components/Button/Button.ts",
    "cssFile": "src/components/Button/Button.css",
    "testFile": "src/components/Button/Button.test.ts"
  },
  {
    "id": "input",
    "name": "Input",
    "category": "input",
    "desc": "text/email/password/number，支持 label/error/hint/required",
    "codeKey": "input",
    "demo": "DemoInput",
    "sourceFile": "src/components/Input/Input.ts",
    "cssFile": "src/components/Input/Input.css",
    "testFile": "src/components/Input/Input.test.ts"
  },
  {
    "id": "textarea",
    "name": "Textarea",
    "category": "input",
    "desc": "多行文本，支持 rows/label/error/hint",
    "codeKey": "textarea",
    "demo": "DemoTextarea",
    "sourceFile": "src/components/Textarea/Textarea.ts",
    "cssFile": "src/components/Textarea/Textarea.css",
    "testFile": "src/components/Textarea/Textarea.test.ts"
  },
  {
    "id": "select",
    "name": "Select",
    "category": "input",
    "desc": "原生下拉选择器",
    "codeKey": "select",
    "demo": "DemoSelect",
    "sourceFile": "src/components/Select/Select.ts",
    "cssFile": "src/components/Select/Select.css",
    "testFile": "src/components/Select/Select.test.ts"
  },
  {
    "id": "select-searchable",
    "name": "Select (searchable)",
    "category": "input",
    "desc": "搜索过滤下拉，输入即搜",
    "codeKey": "select",
    "demo": "DemoSearchableSelect"
  },
  {
    "id": "checkbox",
    "name": "Checkbox",
    "category": "input",
    "desc": "带 label 的复选框，支持 checked/disabled",
    "codeKey": "checkbox",
    "demo": "DemoCheckbox",
    "sourceFile": "src/components/Checkbox/Checkbox.ts",
    "cssFile": "src/components/Checkbox/Checkbox.css",
    "testFile": "src/components/Checkbox/Checkbox.test.ts"
  },
  {
    "id": "switch",
    "name": "Switch",
    "category": "input",
    "desc": "开关切换，视觉替代 checkbox",
    "codeKey": "switch",
    "demo": "DemoSwitch",
    "sourceFile": "src/components/Switch/Switch.ts",
    "cssFile": "src/components/Switch/Switch.css",
    "testFile": "src/components/Switch/Switch.test.ts"
  },
  {
    "id": "radiogroup",
    "name": "RadioGroup",
    "category": "input",
    "desc": "单选组，支持 inline/options/value",
    "codeKey": "radio",
    "demo": "DemoRadio",
    "sourceFile": "src/components/RadioGroup/RadioGroup.ts",
    "cssFile": "src/components/RadioGroup/RadioGroup.css",
    "testFile": "src/components/RadioGroup/RadioGroup.test.ts"
  },
  {
    "id": "segmentedcontrol",
    "name": "SegmentedControl",
    "category": "input",
    "desc": "分段单选（模式切换/筛选/模板），支持 sm/block",
    "codeKey": "segmented",
    "demo": "DemoSegmented",
    "sourceFile": "src/components/SegmentedControl/SegmentedControl.ts",
    "cssFile": "src/components/SegmentedControl/SegmentedControl.css",
    "testFile": "src/components/SegmentedControl/SegmentedControl.test.ts"
  },
  {
    "id": "slider",
    "name": "Slider",
    "category": "input",
    "desc": "范围滑块，支持 min/max/step/label",
    "codeKey": "slider",
    "demo": "DemoSlider",
    "sourceFile": "src/components/Slider/Slider.ts",
    "cssFile": "src/components/Slider/Slider.css",
    "testFile": "src/components/Slider/Slider.test.ts"
  },
  {
    "id": "form",
    "name": "Form",
    "category": "form",
    "desc": "内置验证规则：required/pattern/minLength/自定义",
    "codeKey": "form",
    "demo": "DemoForm",
    "sourceFile": "src/components/Form/Form.ts",
    "cssFile": "src/components/Form/Form.css",
    "testFile": "src/components/Form/Form.test.ts"
  },
  {
    "id": "form-v2",
    "name": "Form 提交",
    "category": "form",
    "desc": "loading 提交 + 校验错误（状态矩阵覆盖）",
    "codeKey": "formSubmit",
    "demo": "DemoFormSubmit"
  },
  {
    "id": "field",
    "name": "Field",
    "category": "form",
    "desc": "label+error+hint 容器",
    "codeKey": "field",
    "demo": "DemoField",
    "sourceFile": "src/components/Field/Field.ts",
    "cssFile": "src/components/Field/Field.css",
    "testFile": "src/components/Field/Field.test.ts"
  },
  {
    "id": "fileupload",
    "name": "FileUpload",
    "category": "editor",
    "desc": "文件上传，拖拽区 + 文件列表 + accept/maxSize",
    "codeKey": "fileUpload",
    "demo": "DemoFileUpload",
    "sourceFile": "src/components/FileUpload/FileUpload.ts",
    "cssFile": "src/components/FileUpload/FileUpload.css",
    "testFile": "src/components/FileUpload/FileUpload.test.ts"
  },
  {
    "id": "fileupload-v2",
    "name": "FileUpload 禁用",
    "category": "editor",
    "desc": "disabled + accept 限定（状态矩阵覆盖）",
    "codeKey": "fileUploadDis",
    "demo": "DemoFileUploadDis"
  },
  {
    "id": "searchinput",
    "name": "SearchInput",
    "category": "input",
    "desc": "搜索输入框，带清除按钮",
    "codeKey": "search",
    "demo": "DemoSearchInput",
    "sourceFile": "src/components/SearchInput/SearchInput.ts",
    "cssFile": "src/components/SearchInput/SearchInput.css",
    "testFile": "src/components/SearchInput/SearchInput.test.ts"
  },
  {
    "id": "progressbar",
    "name": "ProgressBar",
    "category": "feedback",
    "desc": "进度条，支持 label/showValue",
    "codeKey": "progress",
    "demo": "DemoProgress",
    "sourceFile": "src/components/ProgressBar/ProgressBar.ts",
    "cssFile": "src/components/ProgressBar/ProgressBar.css",
    "testFile": "src/components/ProgressBar/ProgressBar.test.ts"
  },
  {
    "id": "inputnumber",
    "name": "InputNumber",
    "category": "input",
    "desc": "数字输入：min/max/step + 增减按钮 + precision",
    "codeKey": "inputNumber",
    "demo": "DemoInputNumber",
    "sourceFile": "src/components/InputNumber/InputNumber.ts",
    "cssFile": "src/components/InputNumber/InputNumber.css",
    "testFile": "src/components/InputNumber/InputNumber.test.ts"
  },
  {
    "id": "passwordinput",
    "name": "PasswordInput",
    "category": "input",
    "desc": "密码输入：眼睛按钮切换可见性",
    "codeKey": "passwordInput",
    "demo": "DemoPasswordInput",
    "sourceFile": "src/components/PasswordInput/PasswordInput.ts",
    "cssFile": "src/components/PasswordInput/PasswordInput.css",
    "testFile": "src/components/PasswordInput/PasswordInput.test.ts"
  },
  {
    "id": "tagsinput",
    "name": "TagsInput",
    "category": "input",
    "desc": "标签输入：回车/逗号添加 + 中文输入法感知",
    "codeKey": "tagsInput",
    "demo": "DemoTagsInput",
    "sourceFile": "src/components/TagsInput/TagsInput.ts",
    "cssFile": "src/components/TagsInput/TagsInput.css",
    "testFile": "src/components/TagsInput/TagsInput.test.ts"
  },
  {
    "id": "tagsinput-v2",
    "name": "TagsInput 限制/错误",
    "category": "input",
    "desc": "maxTags 限制 + error 校验态（状态矩阵覆盖）",
    "codeKey": "tagsInputErr",
    "demo": "DemoTagsInputErr"
  },
  {
    "id": "table",
    "name": "Table",
    "category": "display",
    "desc": "可排序 + 自定义 render + 空状态",
    "codeKey": "table",
    "demo": "DemoTable",
    "sourceFile": "src/components/Table/Table.ts",
    "cssFile": "src/components/Table/Table.css",
    "testFile": "src/components/Table/Table.test.ts"
  },
  {
    "id": "table-v2",
    "name": "Table 行选择",
    "category": "display",
    "desc": "rowSelection 勾选列 + 受控 keys（状态矩阵覆盖）",
    "codeKey": "tableRowSelect",
    "demo": "DemoTableRowSelect"
  },
  {
    "id": "card",
    "name": "Card",
    "category": "core",
    "desc": "容器，支持 default/outlined/clickable",
    "codeKey": "card",
    "demo": "DemoCardShowcase",
    "sourceFile": "src/components/Card/Card.ts",
    "cssFile": "src/components/Card/Card.css",
    "testFile": "src/components/Card/Card.test.ts"
  },
  {
    "id": "badge",
    "name": "Badge",
    "category": "core",
    "desc": "状态标签 + 圆点，6 种 variant",
    "codeKey": "badge",
    "demo": "DemoBadge",
    "sourceFile": "src/components/Badge/Badge.ts",
    "cssFile": "src/components/Badge/Badge.css",
    "testFile": "src/components/Badge/Badge.test.ts"
  },
  {
    "id": "tag",
    "name": "Tag",
    "category": "core",
    "desc": "标签，支持 closable/onClose",
    "codeKey": "tag",
    "demo": "DemoTag",
    "sourceFile": "src/components/Tag/Tag.ts",
    "cssFile": "src/components/Tag/Tag.css",
    "testFile": "src/components/Tag/Tag.test.ts"
  },
  {
    "id": "avatar",
    "name": "Avatar",
    "category": "core",
    "desc": "头像（首字母/图片），3 种 size",
    "codeKey": "avatar",
    "demo": "DemoAvatar",
    "sourceFile": "src/components/Avatar/Avatar.ts",
    "cssFile": "src/components/Avatar/Avatar.css",
    "testFile": "src/components/Avatar/Avatar.test.ts"
  },
  {
    "id": "img",
    "name": "Img",
    "category": "display",
    "desc": "图片 \\<img\\> 组件：fallback / lazy / preview 点击放大",
    "codeKey": "image",
    "demo": "DemoImage",
    "sourceFile": "src/components/Img/Img.ts",
    "cssFile": "src/components/Img/Img.css",
    "testFile": "src/components/Img/Img.test.ts"
  },
  {
    "id": "inview",
    "name": "InView",
    "category": "display",
    "desc": "进入视窗后懒加载内容，支持 IntersectionObserver",
    "codeKey": "inview",
    "demo": "DemoInView",
    "sourceFile": "src/components/InView/InView.ts",
    "cssFile": "src/components/InView/InView.css",
    "testFile": "src/components/InView/InView.test.ts"
  },
  {
    "id": "timeline",
    "name": "Timeline",
    "category": "display",
    "desc": "时间线：节点状态色 + 时间 + 内容（执行日志/审批历史）",
    "codeKey": "timeline",
    "demo": "DemoTimeline",
    "sourceFile": "src/components/Timeline/Timeline.ts",
    "cssFile": "src/components/Timeline/Timeline.css",
    "testFile": "src/components/Timeline/Timeline.test.ts"
  },
  {
    "id": "descriptions",
    "name": "Descriptions",
    "category": "display",
    "desc": "描述列表：label/value 栅格 + bordered + span（详情页）",
    "codeKey": "descriptions",
    "demo": "DemoDescriptions",
    "sourceFile": "src/components/Descriptions/Descriptions.ts",
    "cssFile": "src/components/Descriptions/Descriptions.css",
    "testFile": "src/components/Descriptions/Descriptions.test.ts"
  },
  {
    "id": "descriptions-v2",
    "name": "Descriptions 紧凑",
    "category": "display",
    "desc": "size=small 详情页密度（变体覆盖）",
    "codeKey": "descriptionsSize",
    "demo": "DemoDescriptionsSize"
  },
  {
    "id": "avatargroup",
    "name": "AvatarGroup",
    "category": "core",
    "desc": "头像组：堆叠 + max 溢出 +N",
    "codeKey": "avatarGroup",
    "demo": "DemoAvatarGroup",
    "sourceFile": "src/components/AvatarGroup/AvatarGroup.ts",
    "cssFile": "src/components/AvatarGroup/AvatarGroup.css",
    "testFile": "src/components/AvatarGroup/AvatarGroup.test.ts"
  },
  {
    "id": "markdown",
    "name": "Markdown",
    "category": "display",
    "desc": "AI 回复渲染：安全子集 parser + 代码块 + 链接白名单",
    "codeKey": "markdown",
    "demo": "DemoMarkdown",
    "sourceFile": "src/components/Markdown/Markdown.ts",
    "cssFile": "src/components/Markdown/Markdown.css",
    "testFile": "src/components/Markdown/Markdown.test.ts"
  },
  {
    "id": "codeblock",
    "name": "CodeBlock",
    "category": "display",
    "desc": "代码块：语言标签 + 复制按钮 + 横向滚动",
    "codeKey": "codeblock",
    "demo": "DemoCodeBlock",
    "sourceFile": "src/components/CodeBlock/CodeBlock.ts",
    "cssFile": "src/components/CodeBlock/CodeBlock.css",
    "testFile": "src/components/CodeBlock/CodeBlock.test.ts"
  },
  {
    "id": "logviewer",
    "name": "LogViewer",
    "category": "display",
    "desc": "日志流：ANSI 着色 + 虚拟滚动 + 自动跟随 + 复制",
    "codeKey": "logviewer",
    "demo": "DemoLogViewer",
    "sourceFile": "src/components/LogViewer/LogViewer.ts",
    "cssFile": "src/components/LogViewer/LogViewer.css",
    "testFile": "src/components/LogViewer/LogViewer.test.ts"
  },
  {
    "id": "logviewer-v2",
    "name": "LogViewer 自定义",
    "category": "display",
    "desc": "自定义日志源 + 行号 + 复制（变体覆盖）",
    "codeKey": "logviewerCustom",
    "demo": "DemoLogViewerCustom"
  },
  {
    "id": "jsonviewer",
    "name": "JSONViewer",
    "category": "display",
    "desc": "结构化 JSON：递归折叠 + 类型色 + 路径复制 + 懒展开",
    "codeKey": "jsonviewer",
    "demo": "DemoJSONViewer",
    "sourceFile": "src/components/JSONViewer/JSONViewer.ts",
    "cssFile": "src/components/JSONViewer/JSONViewer.css",
    "testFile": "src/components/JSONViewer/JSONViewer.test.ts"
  },
  {
    "id": "jsonviewer-v2",
    "name": "JSONViewer 深展开",
    "category": "display",
    "desc": "defaultExpandDepth 深度展开嵌套对象（变体覆盖）",
    "codeKey": "jsonviewerDeep",
    "demo": "DemoJSONViewerDeep"
  },
  {
    "id": "diffview",
    "name": "DiffView",
    "category": "display",
    "desc": "代码 diff：LCS 行级对比 + 未变块折叠 + 三态着色",
    "codeKey": "diffview",
    "demo": "DemoDiffView",
    "sourceFile": "src/components/DiffView/DiffView.ts",
    "cssFile": "src/components/DiffView/DiffView.css",
    "testFile": "src/components/DiffView/DiffView.test.ts"
  },
  {
    "id": "diffview-v2",
    "name": "DiffView 标题",
    "category": "display",
    "desc": "oldTitle/newTitle 标记版本对比（变体覆盖）",
    "codeKey": "diffviewBig",
    "demo": "DemoDiffViewBig"
  },
  {
    "id": "sparkline",
    "name": "Sparkline",
    "category": "viz",
    "desc": "迷你趋势线：SVG 自绘 + 归一化 + 平滑曲线 + 面积填充",
    "codeKey": "sparkline",
    "demo": "DemoSparkline",
    "sourceFile": "src/components/Sparkline/Sparkline.ts",
    "cssFile": "src/components/Sparkline/Sparkline.css",
    "testFile": "src/components/Sparkline/Sparkline.test.ts"
  },
  {
    "id": "tour",
    "name": "Tour",
    "category": "overlay",
    "desc": "新手引导：步骤气泡 + 目标高亮 + 遮罩 + 键盘 Escape",
    "codeKey": "tour",
    "demo": "DemoTour",
    "sourceFile": "src/components/Tour/Tour.ts",
    "cssFile": "src/components/Tour/Tour.css",
    "testFile": "src/components/Tour/Tour.test.ts"
  },
  {
    "id": "kanban",
    "name": "Kanban",
    "category": "viz",
    "desc": "看板：原生 DnD 拖拽 + 跨列/重排 + 悬停高亮",
    "codeKey": "kanban",
    "demo": "DemoKanban",
    "sourceFile": "src/components/Kanban/Kanban.ts",
    "cssFile": "src/components/Kanban/Kanban.css",
    "testFile": "src/components/Kanban/Kanban.test.ts"
  },
  {
    "id": "pipeline",
    "name": "Pipeline",
    "category": "viz",
    "desc": "Agent 工作流 DAG：分层布局 + 贝塞尔连线 + 状态语义色 + 环检测",
    "codeKey": "pipeline",
    "demo": "DemoPipeline",
    "sourceFile": "src/components/Pipeline/Pipeline.ts",
    "cssFile": "src/components/Pipeline/Pipeline.css",
    "testFile": "src/components/Pipeline/Pipeline.test.ts"
  },
  {
    "id": "treeselect",
    "name": "TreeSelect",
    "category": "advanced",
    "desc": "树形选择：单选/多选（父子联动）+ 选中 label 回显 + 受控纪律",
    "codeKey": "treeselect",
    "demo": "DemoTreeSelect",
    "sourceFile": "src/components/TreeSelect/TreeSelect.ts",
    "cssFile": "src/components/TreeSelect/TreeSelect.css",
    "testFile": "src/components/TreeSelect/TreeSelect.test.ts"
  },
  {
    "id": "layout",
    "name": "Layout",
    "category": "core",
    "desc": "布局外壳：Sider 折叠 + Header/Content/Footer 骨架（antd Layout / shadcn Sidebar 等价）",
    "codeKey": "layout",
    "demo": "DemoLayout",
    "sourceFile": "src/components/Layout/Layout.ts",
    "cssFile": "src/components/Layout/Layout.css",
    "testFile": "src/components/Layout/Layout.test.ts"
  },
  {
    "id": "layoutheader",
    "name": "LayoutHeader",
    "category": "core",
    "desc": "布局顶栏——Layout 家族（Layout/LayoutHeader/LayoutSider/LayoutContent/LayoutFooter）",
    "sourceFile": "src/components/Layout/Layout.ts",
    "cssFile": "src/components/Layout/Layout.css",
    "testFile": "src/components/Layout/Layout.test.ts"
  },
  {
    "id": "layoutsider",
    "name": "LayoutSider",
    "category": "core",
    "desc": "布局侧栏（可折叠 collapsed/collapsible）——Layout 家族",
    "sourceFile": "src/components/Layout/Layout.ts",
    "cssFile": "src/components/Layout/Layout.css",
    "testFile": "src/components/Layout/Layout.test.ts"
  },
  {
    "id": "layoutcontent",
    "name": "LayoutContent",
    "category": "core",
    "desc": "布局内容区——Layout 家族",
    "sourceFile": "src/components/Layout/Layout.ts",
    "cssFile": "src/components/Layout/Layout.css",
    "testFile": "src/components/Layout/Layout.test.ts"
  },
  {
    "id": "popconfirm",
    "name": "Popconfirm",
    "category": "overlay",
    "desc": "气泡确认：危险操作防误触 + 复用 usePopup 基座",
    "codeKey": "popconfirm",
    "demo": "DemoPopconfirm",
    "sourceFile": "src/components/Popconfirm/Popconfirm.ts",
    "cssFile": "src/components/Popconfirm/Popconfirm.css",
    "testFile": "src/components/Popconfirm/Popconfirm.test.ts"
  },
  {
    "id": "autocomplete",
    "name": "AutoComplete",
    "category": "advanced",
    "desc": "输入联想：自由输入 + 过滤下拉 + 键盘流 + 选中回填",
    "codeKey": "autocomplete",
    "demo": "DemoAutoComplete",
    "sourceFile": "src/components/AutoComplete/AutoComplete.ts",
    "cssFile": "src/components/AutoComplete/AutoComplete.css",
    "testFile": "src/components/AutoComplete/AutoComplete.test.ts"
  },
  {
    "id": "autocomplete-v2",
    "name": "AutoComplete 禁用态",
    "category": "input",
    "desc": "disabled 时不可输入（状态矩阵覆盖）",
    "codeKey": "autocompleteDis",
    "demo": "DemoAutoCompleteDis"
  },
  {
    "id": "link",
    "name": "Link",
    "category": "core",
    "desc": "文字链接：语义色/下划线/disabled/新窗口",
    "codeKey": "link",
    "demo": "DemoLink",
    "sourceFile": "src/components/Link/Link.ts",
    "cssFile": "src/components/Link/Link.css",
    "testFile": "src/components/Link/Link.test.ts"
  },
  {
    "id": "floatbutton",
    "name": "FloatButton",
    "category": "core",
    "desc": "悬浮按钮组：展开状态机 + badge",
    "codeKey": "floatbutton",
    "demo": "DemoFloatButton",
    "sourceFile": "src/components/FloatButton/FloatButton.ts",
    "cssFile": "src/components/FloatButton/FloatButton.css",
    "testFile": "src/components/FloatButton/FloatButton.test.ts"
  },
  {
    "id": "navmenu",
    "name": "NavMenu",
    "category": "navigation",
    "desc": "顶部导航：多级 hover 弹出 + 键盘（shadcn NavigationMenu）",
    "codeKey": "navmenu",
    "demo": "DemoNavMenu",
    "sourceFile": "src/components/NavMenu/NavMenu.ts",
    "cssFile": "src/components/NavMenu/NavMenu.css",
    "testFile": "src/components/NavMenu/NavMenu.test.ts"
  },
  {
    "id": "space",
    "name": "Space",
    "category": "core",
    "desc": "间距容器：size/direction/wrap + split 分隔符",
    "codeKey": "space",
    "demo": "DemoSpace",
    "sourceFile": "src/components/Space/Space.ts",
    "cssFile": "src/components/Space/Space.css",
    "testFile": "src/components/Space/Space.test.ts"
  },
  {
    "id": "grid",
    "name": "Grid",
    "category": "core",
    "desc": "24 栅格 + gutter + flex 容器模式（Row/Col/Flex 等价）",
    "codeKey": "grid",
    "demo": "DemoGrid",
    "sourceFile": "src/components/Grid/Grid.ts",
    "cssFile": "src/components/Grid/Grid.css",
    "testFile": "src/components/Grid/Grid.test.ts"
  },
  {
    "id": "scrollbar",
    "name": "Scrollbar",
    "category": "core",
    "desc": "自定义滚动容器：webkit 样式 + hover 显示",
    "codeKey": "scrollbar",
    "demo": "DemoScrollbar",
    "sourceFile": "src/components/Scrollbar/Scrollbar.ts",
    "cssFile": "src/components/Scrollbar/Scrollbar.css",
    "testFile": "src/components/Scrollbar/Scrollbar.test.ts"
  },
  {
    "id": "alertgroup",
    "name": "AlertGroup",
    "category": "feedback",
    "desc": "通知合并组：≥3 条折叠为 +N，点击展开",
    "codeKey": "alertgroup",
    "demo": "DemoAlertGroup",
    "sourceFile": "src/components/AlertGroup/AlertGroup.ts",
    "cssFile": "src/components/AlertGroup/AlertGroup.css",
    "testFile": "src/components/AlertGroup/AlertGroup.test.ts"
  },
  {
    "id": "statcard-countdown",
    "name": "StatCard Countdown",
    "category": "display",
    "desc": "倒计时模式：剩余 HH:MM:SS + 结束回调",
    "codeKey": "statCountdown",
    "demo": "DemoStatCountdown"
  },
  {
    "id": "messagebubble",
    "name": "MessageBubble",
    "category": "display",
    "desc": "消息气泡：user/assistant + streaming/error 状态 + actions",
    "codeKey": "messageBubble",
    "demo": "DemoMessageBubble",
    "sourceFile": "src/components/MessageBubble/MessageBubble.ts",
    "cssFile": "src/components/MessageBubble/MessageBubble.css",
    "testFile": "src/components/MessageBubble/MessageBubble.test.ts"
  },
  {
    "id": "highlight",
    "name": "Highlight",
    "category": "display",
    "desc": "搜索词高亮：分词渲染 mark，大小写不敏感",
    "codeKey": "highlight",
    "demo": "DemoHighlight",
    "sourceFile": "src/components/Highlight/Highlight.ts",
    "cssFile": "src/components/Highlight/Highlight.css",
    "testFile": "src/components/Highlight/Highlight.test.ts"
  },
  {
    "id": "highlight-v2",
    "name": "Highlight 多词",
    "category": "display",
    "desc": "query 数组多词高亮（变体覆盖）",
    "codeKey": "highlightMulti",
    "demo": "DemoHighlightMulti"
  },
  {
    "id": "list",
    "name": "List",
    "category": "display",
    "desc": "通用列表：renderItem + divided + header/footer/empty",
    "codeKey": "list",
    "demo": "DemoList",
    "sourceFile": "src/components/List/List.ts",
    "cssFile": "src/components/List/List.css",
    "testFile": "src/components/List/List.test.ts"
  },
  {
    "id": "result",
    "name": "Result",
    "category": "feedback",
    "desc": "结果页：success/error/warning/info + extra 操作区",
    "codeKey": "result",
    "demo": "DemoResult",
    "sourceFile": "src/components/Result/Result.ts",
    "cssFile": "src/components/Result/Result.css",
    "testFile": "src/components/Result/Result.test.ts"
  },
  {
    "id": "confirm",
    "name": "Confirm",
    "category": "feedback",
    "desc": "确认对话框，Promise 化 await 调用",
    "codeKey": "confirm",
    "demo": "DemoConfirm",
    "sourceFile": "src/components/Confirm/Confirm.ts",
    "testFile": "src/components/Confirm/Confirm.test.ts"
  },
  {
    "id": "statcard",
    "name": "StatCard",
    "category": "display",
    "desc": "KPI 指标卡，支持 trend/icon",
    "codeKey": "stat",
    "demo": "DemoStatCard",
    "sourceFile": "src/components/StatCard/StatCard.ts",
    "cssFile": "src/components/StatCard/StatCard.css",
    "testFile": "src/components/StatCard/StatCard.test.ts"
  },
  {
    "id": "chart",
    "name": "Chart",
    "category": "viz",
    "desc": "SVG 图表：line/bar/pie/radar/gauge/scatter——零依赖自绘",
    "codeKey": "chart",
    "demo": "DemoChart",
    "sourceFile": "src/components/Chart/Chart.ts",
    "cssFile": "src/components/Chart/Chart.css",
    "testFile": "src/components/Chart/Chart.test.ts"
  },
  {
    "id": "editor",
    "name": "Editor",
    "category": "editor",
    "desc": "富文本编辑器，contentEditable + toolbar，零依赖",
    "codeKey": "editor",
    "demo": "DemoEditor",
    "sourceFile": "src/components/Editor/Editor.ts",
    "cssFile": "src/components/Editor/Editor.css",
    "testFile": "src/components/Editor/Editor.test.ts"
  },
  {
    "id": "filepreview",
    "name": "FilePreview",
    "category": "editor",
    "desc": "文件预览（md/html/pdf/office）——基于事件流，可编辑",
    "demo": "DemoFilePreview",
    "sourceFile": "src/components/FilePreview/FilePreview.ts",
    "cssFile": "src/components/FilePreview/FilePreview.css",
    "testFile": "src/components/FilePreview/FilePreview.test.ts"
  },
  {
    "id": "filepreview-office",
    "name": "FilePreview Office",
    "category": "editor",
    "desc": "office 前端导入/导出（零依赖转换——无需后端）",
    "demo": "DemoFilePreviewOffice"
  },
  {
    "id": "themeswitch",
    "name": "ThemeSwitch",
    "category": "core",
    "desc": "主题切换：auto/light/dark，localStorage 持久化",
    "codeKey": "themeSwitch",
    "demo": "DemoThemeSwitch",
    "sourceFile": "src/components/ThemeSwitch/ThemeSwitch.ts",
    "cssFile": "src/components/ThemeSwitch/ThemeSwitch.css",
    "testFile": "src/components/ThemeSwitch/ThemeSwitch.test.ts"
  },
  {
    "id": "datepicker",
    "name": "DatePicker",
    "category": "advanced",
    "desc": "日期选择器，四种模式：date/datetime/time/range",
    "codeKey": "datepicker",
    "demo": "DemoDatePicker",
    "sourceFile": "src/components/DatePicker/DatePicker.ts",
    "cssFile": "src/components/DatePicker/DatePicker.css",
    "testFile": "src/components/DatePicker/DatePicker.test.ts"
  },
  {
    "id": "modal",
    "name": "Modal",
    "category": "overlay",
    "desc": "自定义宽度 + closable 控制关闭按钮",
    "codeKey": "modal",
    "demo": "DemoModal",
    "sourceFile": "src/components/Modal/Modal.ts",
    "cssFile": "src/components/Modal/Modal.css",
    "testFile": "src/components/Modal/Modal.test.ts"
  },
  {
    "id": "drawer",
    "name": "Drawer",
    "category": "overlay",
    "desc": "侧边面板，左右滑入 + ESC 关闭",
    "codeKey": "drawer",
    "demo": "DemoDrawer",
    "sourceFile": "src/components/Drawer/Drawer.ts",
    "cssFile": "src/components/Drawer/Drawer.css",
    "testFile": "src/components/Drawer/Drawer.test.ts"
  },
  {
    "id": "popover",
    "name": "Popover",
    "category": "overlay",
    "desc": "通用弹出层，click/hover 触发，4 方向",
    "codeKey": "popover",
    "demo": "DemoPopover",
    "sourceFile": "src/components/Popover/Popover.ts",
    "cssFile": "src/components/Popover/Popover.css",
    "testFile": "src/components/Popover/Popover.test.ts"
  },
  {
    "id": "tooltip",
    "name": "Tooltip",
    "category": "overlay",
    "desc": "hover 浮动提示，4 方向",
    "codeKey": "tooltip",
    "demo": "DemoTooltip",
    "sourceFile": "src/components/Tooltip/Tooltip.ts",
    "cssFile": "src/components/Tooltip/Tooltip.css",
    "testFile": "src/components/Tooltip/Tooltip.test.ts"
  },
  {
    "id": "toast",
    "name": "Toast",
    "category": "feedback",
    "desc": "5 种位置 + 自动消失 + 数量限制",
    "codeKey": "toast",
    "demo": "DemoToast",
    "sourceFile": "src/components/Toast/Toast.ts",
    "cssFile": "src/components/Toast/Toast.css",
    "testFile": "src/components/Toast/Toast.test.ts"
  },
  {
    "id": "alert",
    "name": "Alert",
    "category": "feedback",
    "desc": "信息提示条，4 种 variant + closable",
    "codeKey": "alert",
    "demo": "DemoAlert",
    "sourceFile": "src/components/Alert/Alert.ts",
    "cssFile": "src/components/Alert/Alert.css",
    "testFile": "src/components/Alert/Alert.test.ts"
  },
  {
    "id": "loading",
    "name": "Loading",
    "category": "feedback",
    "desc": "加载状态，支持自定义文字",
    "codeKey": "loading",
    "demo": "DemoLoading",
    "sourceFile": "src/components/Loading/Loading.ts",
    "cssFile": "src/components/Loading/Loading.css",
    "testFile": "src/components/Loading/Loading.test.ts"
  },
  {
    "id": "skeleton",
    "name": "Skeleton",
    "category": "display",
    "desc": "text/circle/rect/image/avatar/table 六种变体",
    "codeKey": "skeleton",
    "demo": "DemoSkeleton",
    "sourceFile": "src/components/Skeleton/Skeleton.ts",
    "cssFile": "src/components/Skeleton/Skeleton.css",
    "testFile": "src/components/Skeleton/Skeleton.test.ts"
  },
  {
    "id": "emptystate",
    "name": "EmptyState",
    "category": "feedback",
    "desc": "空状态占位，支持 icon/text/hint/action",
    "codeKey": "empty",
    "demo": "DemoEmptyState",
    "sourceFile": "src/components/EmptyState/EmptyState.ts",
    "cssFile": "src/components/EmptyState/EmptyState.css",
    "testFile": "src/components/EmptyState/EmptyState.test.ts"
  },
  {
    "id": "breadcrumb",
    "name": "Breadcrumb",
    "category": "navigation",
    "desc": "面包屑导航，支持 aria-current",
    "codeKey": "breadcrumb",
    "demo": "DemoBreadcrumb",
    "sourceFile": "src/components/Breadcrumb/Breadcrumb.ts",
    "cssFile": "src/components/Breadcrumb/Breadcrumb.css",
    "testFile": "src/components/Breadcrumb/Breadcrumb.test.ts"
  },
  {
    "id": "menu",
    "name": "Menu",
    "category": "navigation",
    "desc": "侧栏导航：分组 + 图标 + 选中态 + 方向键",
    "codeKey": "menu",
    "demo": "DemoMenu",
    "sourceFile": "src/components/Menu/Menu.ts",
    "cssFile": "src/components/Menu/Menu.css",
    "testFile": "src/components/Menu/Menu.test.ts"
  },
  {
    "id": "tabs",
    "name": "Tabs",
    "category": "navigation",
    "desc": "标签页切换，支持 active/onChange",
    "codeKey": "tabs",
    "demo": "DemoTabs",
    "sourceFile": "src/components/Tabs/Tabs.ts",
    "cssFile": "src/components/Tabs/Tabs.css",
    "testFile": "src/components/Tabs/Tabs.test.ts"
  },
  {
    "id": "dropdown",
    "name": "Dropdown",
    "category": "overlay",
    "desc": "下拉菜单，支持 danger variant",
    "codeKey": "dropdown",
    "demo": "DemoDropdown",
    "sourceFile": "src/components/Dropdown/Dropdown.ts",
    "cssFile": "src/components/Dropdown/Dropdown.css",
    "testFile": "src/components/Dropdown/Dropdown.test.ts"
  },
  {
    "id": "pagination",
    "name": "Pagination",
    "category": "navigation",
    "desc": "分页器，自动计算页码范围",
    "codeKey": "pagination",
    "demo": "DemoPagination",
    "sourceFile": "src/components/Pagination/Pagination.ts",
    "cssFile": "src/components/Pagination/Pagination.css",
    "testFile": "src/components/Pagination/Pagination.test.ts"
  },
  {
    "id": "steps",
    "name": "Steps",
    "category": "navigation",
    "desc": "分步指示器，支持 active/current",
    "codeKey": "steps",
    "demo": "DemoSteps",
    "sourceFile": "src/components/Steps/Steps.ts",
    "cssFile": "src/components/Steps/Steps.css",
    "testFile": "src/components/Steps/Steps.test.ts"
  },
  {
    "id": "accordion",
    "name": "Accordion",
    "category": "navigation",
    "desc": "折叠面板，支持多个 items",
    "codeKey": "accordion",
    "demo": "DemoAccordion",
    "sourceFile": "src/components/Accordion/Accordion.ts",
    "cssFile": "src/components/Accordion/Accordion.css",
    "testFile": "src/components/Accordion/Accordion.test.ts"
  },
  {
    "id": "aichat",
    "name": "AiChat",
    "category": "ai",
    "desc": "useChat + 标准对话界面：流式 token / 工具卡 / 审批卡 / 自动滚动，协议对页面透明",
    "codeKey": "aichat",
    "demo": "DemoAiChat",
    "sourceFile": "src/components/AiChat/AiChat.ts",
    "cssFile": "src/components/AiChat/AiChat.css",
    "testFile": "src/components/AiChat/AiChat.test.ts"
  },
  {
    "id": "chatinput",
    "name": "ChatInput",
    "category": "ai",
    "desc": "独立聊天输入条（AiChat 抽取）：单行/多行 + streaming 停止 + IME 安全——不自带聊天逻辑",
    "codeKey": "chatinput",
    "demo": "DemoChatInput",
    "sourceFile": "src/components/ChatInput/ChatInput.ts",
    "cssFile": "src/components/ChatInput/ChatInput.css",
    "testFile": "src/components/ChatInput/ChatInput.test.ts"
  },
  {
    "id": "authpage",
    "name": "AuthPage",
    "category": "ai",
    "desc": "认证页骨架：居中卡片 + logo + 表单插槽 + 错误条 + 提交 loading（登录/注册复用）",
    "codeKey": "authpage",
    "demo": "DemoAuthPage",
    "sourceFile": "src/components/AuthPage/AuthPage.ts",
    "testFile": "src/components/AuthPage/AuthPage.test.ts"
  },
  {
    "id": "toolcallcard",
    "name": "ToolCallCard",
    "category": "ai",
    "desc": "工具调用卡片：running / ok / error 状态机（call/progress/result 三字段驱动）",
    "codeKey": "toolcall",
    "demo": "DemoToolCallCard",
    "sourceFile": "src/components/ToolCallCard/ToolCallCard.ts",
    "cssFile": "src/components/ToolCallCard/ToolCallCard.css",
    "testFile": "src/components/ToolCallCard/ToolCallCard.test.ts"
  },
  {
    "id": "jsonschemaform",
    "name": "JsonSchemaForm",
    "category": "form",
    "desc": "JSON Schema → 参数输入表单：类型映射 + 必填/范围校验 + 嵌套/数组（AI 工具参数输入面）",
    "codeKey": "jsonschemaform",
    "demo": "DemoJsonSchemaForm",
    "sourceFile": "src/components/JsonSchemaForm/JsonSchemaForm.ts",
    "cssFile": "src/components/JsonSchemaForm/JsonSchemaForm.css",
    "testFile": "src/components/JsonSchemaForm/JsonSchemaForm.test.ts"
  },
  {
    "id": "reasoningblock",
    "name": "ReasoningBlock",
    "category": "ai",
    "desc": "CoT 推理折叠展示：aria-expanded + 键盘可达 + 流式脉冲（thinking 模式 reasoning_content）",
    "codeKey": "reasoningblock",
    "demo": "DemoReasoningBlock",
    "sourceFile": "src/components/ReasoningBlock/ReasoningBlock.ts",
    "cssFile": "src/components/ReasoningBlock/ReasoningBlock.css",
    "testFile": "src/components/ReasoningBlock/ReasoningBlock.test.ts"
  },
  {
    "id": "citationcard",
    "name": "CitationCard",
    "category": "ai",
    "desc": "RAG 引用来源：折叠「引用 N 条」+ 条目列表（序号/标题/来源/片段/链接）+ 溢出 +N",
    "codeKey": "citationcard",
    "demo": "DemoCitationCard",
    "sourceFile": "src/components/CitationCard/CitationCard.ts",
    "cssFile": "src/components/CitationCard/CitationCard.css",
    "testFile": "src/components/CitationCard/CitationCard.test.ts"
  },
  {
    "id": "sessionlist",
    "name": "SessionList",
    "category": "ai",
    "desc": "会话管理列表：分组（今天/昨天/更早）+ 搜索 + 选中 + 重命名/删除/新建 + 键盘导航",
    "codeKey": "sessionlist",
    "demo": "DemoSessionList",
    "sourceFile": "src/components/SessionList/SessionList.ts",
    "cssFile": "src/components/SessionList/SessionList.css",
    "testFile": "src/components/SessionList/SessionList.test.ts"
  },
  {
    "id": "approvalcard",
    "name": "ApprovalCard",
    "category": "ai",
    "desc": "HITL 审批卡片：pending 可批/拒 + 修改参数（JsonSchemaForm）· approved/rejected/timeout 终态",
    "codeKey": "approval",
    "demo": "DemoApprovalCard",
    "sourceFile": "src/components/ApprovalCard/ApprovalCard.ts",
    "cssFile": "src/components/ApprovalCard/ApprovalCard.css",
    "testFile": "src/components/ApprovalCard/ApprovalCard.test.ts"
  },
  {
    "id": "pageheader",
    "name": "PageHeader",
    "category": "navigation",
    "desc": "页面标题栏，支持 sub + 右侧操作区 + display 大标题",
    "codeKey": "pageheader",
    "demo": "DemoPageHeader",
    "sourceFile": "src/components/PageHeader/PageHeader.ts",
    "cssFile": "src/components/PageHeader/PageHeader.css",
    "testFile": "src/components/PageHeader/PageHeader.test.ts"
  },
  {
    "id": "icon",
    "name": "Icon",
    "category": "core",
    "desc": "stroke SVG 图标集，currentColor 着色，随字号缩放",
    "codeKey": "icon",
    "demo": "DemoIcon",
    "sourceFile": "src/components/Icon/Icon.ts",
    "cssFile": "src/components/Icon/Icon.css",
    "testFile": "src/components/Icon/Icon.test.ts"
  },
  {
    "id": "divider",
    "name": "Divider",
    "category": "core",
    "desc": "分割线，支持 horizontal/vertical/带文字",
    "codeKey": "divider",
    "demo": "DemoDivider",
    "sourceFile": "src/components/Divider/Divider.ts",
    "cssFile": "src/components/Divider/Divider.css",
    "testFile": "src/components/Divider/Divider.test.ts"
  },
  {
    "id": "app",
    "name": "多应用（app 节点）",
    "category": "ai",
    "desc": "父应用嵌入子应用：注册表 + 独立状态 + app:* 边界事件（appId 可区分——同流全链路）",
    "demo": "DemoApp"
  },
  {
    "id": "rate",
    "name": "Rate",
    "category": "input",
    "desc": "评分：键盘方向键 / allowClear / readOnly，新增 star 图标",
    "codeKey": "rate",
    "demo": "DemoRate",
    "sourceFile": "src/components/Rate/Rate.ts",
    "cssFile": "src/components/Rate/Rate.css",
    "testFile": "src/components/Rate/Rate.test.ts"
  },
  {
    "id": "typography",
    "name": "Typography",
    "category": "core",
    "desc": "Title/Text/Paragraph：语义标签 + 语义色 -text 变体 + mark/code/删除线",
    "codeKey": "typography",
    "demo": "DemoTypography",
    "sourceFile": "src/components/Typography/Typography.ts",
    "cssFile": "src/components/Typography/Typography.css",
    "testFile": "src/components/Typography/Typography.test.ts"
  },
  {
    "id": "label",
    "name": "Label",
    "category": "core",
    "desc": "独立标签（required 星号）+ 宽高比容器（内容填满）",
    "codeKey": "label",
    "demo": "DemoLabel",
    "sourceFile": "src/components/Label/Label.ts",
    "cssFile": "src/components/Label/Label.css",
    "testFile": "src/components/Label/Label.test.ts"
  },
  {
    "id": "aspectratio",
    "name": "AspectRatio",
    "category": "core",
    "desc": "独立标签（required 星号）+ 宽高比容器（内容填满）",
    "codeKey": "label",
    "demo": "DemoAspectRatio",
    "sourceFile": "src/components/AspectRatio/AspectRatio.ts",
    "cssFile": "src/components/AspectRatio/AspectRatio.css",
    "testFile": "src/components/AspectRatio/AspectRatio.test.ts"
  },
  {
    "id": "toggle-togglegroup",
    "name": "Toggle / ToggleGroup",
    "category": "input",
    "desc": "切换按钮：single/multiple 双模式（shadcn 对齐）",
    "codeKey": "togglegroup",
    "demo": "DemoToggleGroup",
    "sourceFile": "src/components/ToggleGroup/ToggleGroup.ts",
    "cssFile": "src/components/ToggleGroup/ToggleGroup.css",
    "testFile": "src/components/ToggleGroup/ToggleGroup.test.ts"
  },
  {
    "id": "checkboxgroup",
    "name": "CheckboxGroup",
    "category": "input",
    "desc": "复选框组：数组受控 + 栅格列数（antd Checkbox.Group）",
    "codeKey": "checkboxgroup",
    "demo": "DemoCheckboxGroup",
    "sourceFile": "src/components/CheckboxGroup/CheckboxGroup.ts",
    "cssFile": "src/components/CheckboxGroup/CheckboxGroup.css",
    "testFile": "src/components/CheckboxGroup/CheckboxGroup.test.ts"
  },
  {
    "id": "pininput",
    "name": "PinInput",
    "category": "input",
    "desc": "验证码输入：自动聚焦/粘贴分派/Backspace 回退（shadcn InputOTP）",
    "codeKey": "pininput",
    "demo": "DemoPinInput",
    "sourceFile": "src/components/PinInput/PinInput.ts",
    "cssFile": "src/components/PinInput/PinInput.css",
    "testFile": "src/components/PinInput/PinInput.test.ts"
  },
  {
    "id": "pininput-v2",
    "name": "PinInput 禁用态",
    "category": "input",
    "desc": "disabled 不可编辑（状态矩阵覆盖）",
    "codeKey": "pininputDis",
    "demo": "DemoPinInputDis"
  },
  {
    "id": "copybutton",
    "name": "CopyButton",
    "category": "core",
    "desc": "复制按钮：clipboard + execCommand 降级 + 成功状态机",
    "codeKey": "copybtn",
    "demo": "DemoCopyButton",
    "sourceFile": "src/components/CopyButton/CopyButton.ts",
    "cssFile": "src/components/CopyButton/CopyButton.css",
    "testFile": "src/components/CopyButton/CopyButton.test.ts"
  },
  {
    "id": "colorpicker",
    "name": "ColorPicker",
    "category": "overlay",
    "desc": "颜色选择：预设色板 + hex 输入（Popover 弹层）",
    "codeKey": "colorpicker",
    "demo": "DemoColorPicker",
    "sourceFile": "src/components/ColorPicker/ColorPicker.ts",
    "cssFile": "src/components/ColorPicker/ColorPicker.css",
    "testFile": "src/components/ColorPicker/ColorPicker.test.ts"
  },
  {
    "id": "hovercard",
    "name": "HoverCard",
    "category": "overlay",
    "desc": "悬停富内容卡：openDelay 延迟 + 任意 VNode（shadcn）",
    "codeKey": "hovercard",
    "demo": "DemoHoverCard",
    "sourceFile": "src/components/HoverCard/HoverCard.ts",
    "cssFile": "src/components/HoverCard/HoverCard.css",
    "testFile": "src/components/HoverCard/HoverCard.test.ts"
  },
  {
    "id": "notification",
    "name": "Notification",
    "category": "feedback",
    "desc": "队列式通知：notification.success/error/warning 命令式（antd 对齐）",
    "codeKey": "notification",
    "demo": "DemoNotification",
    "sourceFile": "src/components/Notification/Notification.ts",
    "cssFile": "src/components/Notification/Notification.css",
    "testFile": "src/components/Notification/Notification.test.ts"
  },
  {
    "id": "backtop",
    "name": "BackTop",
    "category": "navigation",
    "desc": "回到顶部（滚动超 400px 显示）+ 固定导航（距顶 80px 钉住）",
    "codeKey": "backtop",
    "demo": "DemoBackTop",
    "sourceFile": "src/components/BackTop/BackTop.ts",
    "cssFile": "src/components/BackTop/BackTop.css",
    "testFile": "src/components/BackTop/BackTop.test.ts"
  },
  {
    "id": "affix",
    "name": "Affix",
    "category": "navigation",
    "desc": "回到顶部（滚动超 400px 显示）+ 固定导航（距顶 80px 钉住）",
    "codeKey": "backtop",
    "demo": "DemoAffix",
    "sourceFile": "src/components/Affix/Affix.ts",
    "cssFile": "src/components/Affix/Affix.css",
    "testFile": "src/components/Affix/Affix.test.ts"
  },
  {
    "id": "anchor",
    "name": "Anchor",
    "category": "navigation",
    "desc": "锚点导航：滚动高亮跟随 + 点击平滑滚动",
    "codeKey": "anchor",
    "demo": "DemoAnchor",
    "sourceFile": "src/components/Anchor/Anchor.ts",
    "cssFile": "src/components/Anchor/Anchor.css",
    "testFile": "src/components/Anchor/Anchor.test.ts"
  },
  {
    "id": "contextmenu",
    "name": "ContextMenu",
    "category": "overlay",
    "desc": "右键菜单：光标定位 + 方向键 + danger 变体（shadcn）",
    "codeKey": "contextmenu",
    "demo": "DemoContextMenu",
    "sourceFile": "src/components/ContextMenu/ContextMenu.ts",
    "cssFile": "src/components/ContextMenu/ContextMenu.css",
    "testFile": "src/components/ContextMenu/ContextMenu.test.ts"
  },
  {
    "id": "mentions",
    "name": "Mentions",
    "category": "advanced",
    "desc": "@提及：composition 抑制 + 过滤插入（antd Mentions）",
    "codeKey": "mentions",
    "demo": "DemoMentions",
    "sourceFile": "src/components/Mentions/Mentions.ts",
    "cssFile": "src/components/Mentions/Mentions.css",
    "testFile": "src/components/Mentions/Mentions.test.ts"
  },
  {
    "id": "mentions-v2",
    "name": "Mentions 禁用态",
    "category": "input",
    "desc": "disabled 时不可输入（状态矩阵覆盖）",
    "codeKey": "mentionsDis",
    "demo": "DemoMentionsDis"
  },
  {
    "id": "collapse",
    "name": "Collapse",
    "category": "navigation",
    "desc": "行内折叠：异步 loading + extra 操作区（区别于 Accordion）",
    "codeKey": "collapse",
    "demo": "DemoCollapse",
    "sourceFile": "src/components/Collapse/Collapse.ts",
    "cssFile": "src/components/Collapse/Collapse.css",
    "testFile": "src/components/Collapse/Collapse.test.ts"
  },
  {
    "id": "tree",
    "name": "Tree",
    "category": "advanced",
    "desc": "树形：递归模型 + 勾选父子联动 + indeterminate（antd/EP Tree）",
    "codeKey": "tree",
    "demo": "DemoToggleTree",
    "sourceFile": "src/components/Tree/Tree.ts",
    "cssFile": "src/components/Tree/Tree.css",
    "testFile": "src/components/Tree/Tree.test.ts"
  },
  {
    "id": "tree-v2",
    "name": "Tree 勾选",
    "category": "advanced",
    "desc": "checkable 父子联动 + 受控 checkedKeys（变体覆盖）",
    "codeKey": "treeCheck",
    "demo": "DemoToggleTreeCheck"
  },
  {
    "id": "cascader",
    "name": "Cascader",
    "category": "advanced",
    "desc": "级联选择：多列面板逐级推进（antd/EP Cascader）",
    "codeKey": "cascader",
    "demo": "DemoCascader",
    "sourceFile": "src/components/Cascader/Cascader.ts",
    "cssFile": "src/components/Cascader/Cascader.css",
    "testFile": "src/components/Cascader/Cascader.test.ts"
  },
  {
    "id": "cascader-v2",
    "name": "Cascader 禁用/错误",
    "category": "advanced",
    "desc": "disabled + error 校验态（状态矩阵覆盖）",
    "codeKey": "cascaderDis",
    "demo": "DemoCascaderDis"
  },
  {
    "id": "transfer",
    "name": "Transfer",
    "category": "advanced",
    "desc": "穿梭框：双列表 + 选中移动（antd/EP Transfer）",
    "codeKey": "transfer",
    "demo": "DemoTransfer",
    "sourceFile": "src/components/Transfer/Transfer.ts",
    "cssFile": "src/components/Transfer/Transfer.css",
    "testFile": "src/components/Transfer/Transfer.test.ts"
  },
  {
    "id": "command",
    "name": "Command",
    "category": "overlay",
    "desc": "命令面板：⌘K 全局快捷键 + 键盘流（shadcn Command）",
    "codeKey": "command",
    "demo": "DemoCommand",
    "sourceFile": "src/components/Command/Command.ts",
    "cssFile": "src/components/Command/Command.css",
    "testFile": "src/components/Command/Command.test.ts"
  },
  {
    "id": "menubar",
    "name": "Menubar",
    "category": "navigation",
    "desc": "水平菜单栏：←→ 切换 + ↓ 展开（shadcn Menubar）",
    "codeKey": "menubar",
    "demo": "DemoMenubar",
    "sourceFile": "src/components/Menubar/Menubar.ts",
    "cssFile": "src/components/Menubar/Menubar.css",
    "testFile": "src/components/Menubar/Menubar.test.ts"
  },
  {
    "id": "carousel",
    "name": "Carousel",
    "category": "virtual",
    "desc": "轮播：箭头/圆点/循环 + 自动播放（三库共识）",
    "codeKey": "carousel",
    "demo": "DemoCarousel",
    "sourceFile": "src/components/Carousel/Carousel.ts",
    "cssFile": "src/components/Carousel/Carousel.css",
    "testFile": "src/components/Carousel/Carousel.test.ts"
  },
  {
    "id": "resizable",
    "name": "Resizable",
    "category": "virtual",
    "desc": "拖拽分割面板：pointer + 键盘方向键 + clamp（shadcn）",
    "codeKey": "resizable",
    "demo": "DemoResizable",
    "sourceFile": "src/components/Resizable/Resizable.ts",
    "cssFile": "src/components/Resizable/Resizable.css",
    "testFile": "src/components/Resizable/Resizable.test.ts"
  },
  {
    "id": "calendar",
    "name": "Calendar",
    "category": "advanced",
    "desc": "月历：事件点 + 月切换 + 日期选择（antd/EP Calendar）",
    "codeKey": "calendar",
    "demo": "DemoCalendar",
    "sourceFile": "src/components/Calendar/Calendar.ts",
    "cssFile": "src/components/Calendar/Calendar.css",
    "testFile": "src/components/Calendar/Calendar.test.ts"
  },
  {
    "id": "calendar-v2",
    "name": "Calendar 事件",
    "category": "advanced",
    "desc": "事件标记 + 日期选择交互（变体覆盖）",
    "codeKey": "calendarEvents",
    "demo": "DemoCalendarEvents"
  },
  {
    "id": "watermark",
    "name": "Watermark",
    "category": "display",
    "desc": "水印：canvas 平铺绘制 + overlay（antd Watermark）",
    "codeKey": "watermark",
    "demo": "DemoWatermark",
    "sourceFile": "src/components/Watermark/Watermark.ts",
    "cssFile": "src/components/Watermark/Watermark.css",
    "testFile": "src/components/Watermark/Watermark.test.ts"
  },
  {
    "id": "virtuallist",
    "name": "VirtualList",
    "category": "virtual",
    "desc": "虚拟列表：spacer + 可见窗口，200 条只渲染 ~12 个 DOM",
    "codeKey": "virtuallist",
    "demo": "DemoVirtualList",
    "sourceFile": "src/components/VirtualList/VirtualList.ts",
    "cssFile": "src/components/VirtualList/VirtualList.css",
    "testFile": "src/components/VirtualList/VirtualList.test.ts"
  },
  {
    "id": "virtualtable",
    "name": "VirtualTable",
    "category": "virtual",
    "desc": "虚拟表格：10k 行固定表头 + 可见窗口渲染 + 排序",
    "codeKey": "virtualtable",
    "demo": "DemoVirtualTable",
    "sourceFile": "src/components/VirtualTable/VirtualTable.ts",
    "cssFile": "src/components/VirtualTable/VirtualTable.css",
    "testFile": "src/components/VirtualTable/VirtualTable.test.ts"
  },
  {
    "id": "virtualtable-v2",
    "name": "VirtualTable 大数据",
    "category": "virtual",
    "desc": "10 万行虚拟滚动（只渲染可见窗口——性能展示）",
    "codeKey": "virtualtableBig",
    "demo": "DemoVirtualTableBig"
  },
  {
    "id": "infinitescroll",
    "name": "InfiniteScroll",
    "category": "virtual",
    "desc": "无限滚动：底部哨兵触底加载 + loading/end 态",
    "codeKey": "infinitescroll",
    "demo": "DemoInfiniteScroll",
    "sourceFile": "src/components/InfiniteScroll/InfiniteScroll.ts",
    "cssFile": "src/components/InfiniteScroll/InfiniteScroll.css",
    "testFile": "src/components/InfiniteScroll/InfiniteScroll.test.ts"
  },
  {
    "id": "infinitescroll-v2",
    "name": "InfiniteScroll 失败重试",
    "category": "virtual",
    "desc": "加载失败提示 + 滚动重试（状态矩阵覆盖）",
    "codeKey": "infinitescrollRetry",
    "demo": "DemoInfiniteScrollRetry"
  },
  {
    "id": "qrcode",
    "name": "QRCode",
    "category": "display",
    "desc": "二维码：自研 QR 编码（Reed-Solomon + 8 掩码）零依赖 SVG",
    "codeKey": "qrcode",
    "demo": "DemoQRCode",
    "sourceFile": "src/components/QRCode/QRCode.ts",
    "testFile": "src/components/QRCode/QRCode.test.ts"
  },
  {
    "id": "sheetgrid",
    "name": "SheetGrid",
    "category": "editor",
    "desc": "weifuwu/components/SheetGrid — xlsx 网格编辑器（ODES 事件流底座） 设计（design/office-events-plan.md）：文档 = fold(事件流)——SheetGrid 的每个",
    "sourceFile": "src/components/SheetGrid/SheetGrid.ts",
    "cssFile": "src/components/SheetGrid/SheetGrid.css",
    "testFile": "src/components/SheetGrid/SheetGrid.test.ts"
  },
  {
    "id": "slidecanvas",
    "name": "SlideCanvas",
    "category": "editor",
    "desc": "weifuwu/components/SlideCanvas — pptx 画布编辑器（ODES 事件流——阶段 3） 设计（design/office-events-plan.md）：文档 = fold(事件流)——每个编辑 =",
    "sourceFile": "src/components/SlideCanvas/SlideCanvas.ts",
    "cssFile": "src/components/SlideCanvas/SlideCanvas.css",
    "testFile": "src/components/SlideCanvas/SlideCanvas.test.ts"
  },
  {
    "id": "togglegroup",
    "name": "ToggleGroup",
    "category": "input",
    "desc": "（无 demo 卡片——组件目录存在）",
    "sourceFile": "src/components/ToggleGroup/ToggleGroup.ts",
    "cssFile": "src/components/ToggleGroup/ToggleGroup.css",
    "testFile": "src/components/ToggleGroup/ToggleGroup.test.ts"
  },
  {
    "id": "title",
    "name": "Title",
    "category": "core",
    "desc": "标题排版（语义标签 + 语义色 -text 变体）——Typography 家族",
    "sourceFile": "src/components/Typography/Typography.ts",
    "cssFile": "src/components/Typography/Typography.css",
    "testFile": "src/components/Typography/Typography.test.ts"
  },
  {
    "id": "text",
    "name": "Text",
    "category": "core",
    "desc": "正文排版（语义色 -text 变体 + mark/code/删除线）——Typography 家族",
    "sourceFile": "src/components/Typography/Typography.ts",
    "cssFile": "src/components/Typography/Typography.css",
    "testFile": "src/components/Typography/Typography.test.ts"
  },
  {
    "id": "paragraph",
    "name": "Paragraph",
    "category": "core",
    "desc": "段落排版——Typography 家族",
    "sourceFile": "src/components/Typography/Typography.ts",
    "cssFile": "src/components/Typography/Typography.css",
    "testFile": "src/components/Typography/Typography.test.ts"
  }
,
  {
    "id": "tabbar",
    "name": "TabBar",
    "category": "navigation",
    "desc": "底部标签栏——移动端 App 主导航（3-5 tab + icon/badge/受控激活 + safe-area 避让）",
    "sourceFile": "src/components/TabBar/TabBar.ts",
    "cssFile": "src/components/TabBar/TabBar.css",
    "testFile": "src/components/TabBar/TabBar.test.ts"
  }
,
  {
    "id": "actionsheet",
    "name": "ActionSheet",
    "category": "overlay",
    "desc": "动作面板——移动端底部滑出（命令列表 + 取消按钮，usePopup 会话级模态）",
    "sourceFile": "src/components/ActionSheet/ActionSheet.ts",
    "cssFile": "src/components/ActionSheet/ActionSheet.css",
    "testFile": "src/components/ActionSheet/ActionSheet.test.ts"
  }
]
