services:
  adminer:
    image: adminer
    ports:
      - 30080:8080
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  pgvector:
    image: pgvector/pgvector:pg18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: demo
  redis:
    image: redis
    ports:
      - '6379:6379'
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ':9001'
    volumes:
      - minio-data:/data

volumes:
  minio-data:
