services:
  adminer:
    image: adminer
    ports:
      - 30080:8080
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  pgvector:
    image: pgvector/pgvector:pg18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: demo
  redis:
    image: redis
    ports:
      - '6379:6379'
