// Primitives
export { createFocusTrap, createClickAway, scrollLock, rovingTabIndex, createFloating } from './primitives/index.ts'
export type { Placement, FloatingOptions } from './primitives/index.ts'

// Utilities
export { cn } from './cn.ts'

// Phase 1 — Pure CSS
export { Button } from './button.tsx'
export type { ButtonProps } from './button.tsx'
export { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from './card.tsx'
export type { CardProps, CardHeaderProps, CardTitleProps, CardDescriptionProps, CardContentProps, CardFooterProps } from './card.tsx'
export { Divider } from './divider.tsx'
export type { DividerProps } from './divider.tsx'
export { Spinner } from './spinner.tsx'
export type { SpinnerProps } from './spinner.tsx'
export { Skeleton } from './skeleton.tsx'
export type { SkeletonProps } from './skeleton.tsx'
export { Badge } from './badge.tsx'
export type { BadgeProps } from './badge.tsx'
export { Avatar, AvatarGroup } from './avatar.tsx'
export type { AvatarProps, AvatarGroupProps } from './avatar.tsx'
export { Alert } from './alert.tsx'
export type { AlertProps } from './alert.tsx'
export { Progress } from './progress.tsx'
export type { ProgressProps } from './progress.tsx'
export { Space } from './space.tsx'
export type { SpaceProps } from './space.tsx'
export { Tag } from './tag.tsx'
export type { TagProps } from './tag.tsx'
export { Empty } from './empty.tsx'
export type { EmptyProps } from './empty.tsx'

// Phase 2 — Signal-driven
export { Tabs, TabList, Tab, TabPanel } from './tabs.tsx'
export type { TabsProps, TabListProps, TabProps, TabPanelProps } from './tabs.tsx'
export { Accordion, AccordionItem } from './accordion.tsx'
export type { AccordionProps, AccordionItemProps } from './accordion.tsx'
export { Switch } from './switch.tsx'
export type { SwitchProps } from './switch.tsx'
export { Input } from './input.tsx'
export type { InputProps } from './input.tsx'

// Phase 3 — Portal + primitives
export { Modal } from './modal.tsx'
export type { ModalProps } from './modal.tsx'
export { Dropdown } from './dropdown.tsx'
export type { DropdownProps, DropdownItem } from './dropdown.tsx'
export { toast, ToastContainer } from './toast.tsx'
export type { ToastMessage, ToastOptions } from './toast.tsx'
