import { z, f, type ZodRawShape } from 'weifuwu'
import { AGENT_TYPES } from './shapes.ts'

// 声明式 Schema（DDL 算子化）——schema.sql 事实源迁移（生成脚手架——人工校验）
export const AGENT_PLATFORM_SCHEMA: import('weifuwu').SchemaModule = {
  extensions: ['vector'],
  // W4：枚举值派生自 shapes AGENT_TYPES（单源——不再手写三面）
  enums: [{ name: 'agent_type', values: [...AGENT_TYPES] }],
  tables: [
    {
      name: 'agents',
      columns: {
        id: f.pk(z.uuid()),
        app_id: z.uuid().meta({ notNull: true }),
        type: z.enum(['ai','user','webhook','knowledge_base','department']).meta({ notNull: true }),
        name: z.string().meta({ notNull: true }),
        avatar_url: z.string().nullable(),
        description: z.string().nullable(),
        role_label: z.string().nullable(),
        expertise: z.string().nullable(),
        model: z.string().nullable(),
        system_prompt: z.string().nullable(),
        temperature: z.number().meta({ default: 0.7 }).nullable(),
        max_tokens: z.number().int().meta({ default: 2048 }).nullable(),
        human_in_the_loop: z.boolean().meta({ default: false }).nullable(),
        user_id: z.uuid().nullable(),
        webhook_url: z.string().nullable(),
        webhook_secret: z.string().nullable(),
        webhook_retry_count: z.number().int().meta({ default: 3 }).nullable(),
        im_bind_dept: z.uuid().nullable(),
        chunk_size: z.number().int().meta({ default: 500 }).nullable(),
        chunk_overlap: z.number().int().meta({ default: 50 }).nullable(),
        tools: z.json().meta({ default: "[]" }).nullable(),
        department_id: z.uuid().nullable(),
        monthly_token_quota: z.number().int().meta({ notNull: true, default: 0 }),
        is_active: z.boolean().meta({ notNull: true, default: true }),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
        updated_at: z.date().meta({ notNull: true, default: 'now' }),
        webhook_platform: z.string().meta({ notNull: true, default: "generic" }),
        risk_policy: z.string().meta({ notNull: true, default: "auto" }),
        light_model: z.string().nullable(),
        workspace_path: z.string().nullable(),
        allow_file_tools: z.boolean().meta({ notNull: true, default: false }),
        allow_command_exec: z.boolean().meta({ notNull: true, default: false }),
        allow_network: z.boolean().meta({ notNull: true, default: true }),
        approval_policy: z.string().meta({ notNull: true, default: 'auto' }),
        kb_id: z.uuid().nullable(),
        template_slug: z.string().nullable(),
      },
      columnTypes: {
        type: 'agent_type',
      },
      indexes: [
        { cols: ['app_id'], name: 'idx_agents_app' },
        { cols: ['type'], name: 'idx_agents_type' },
      ],
    },
    {
      name: 'departments',
      columns: {
        id: f.pk(z.uuid()),
        app_id: z.uuid().meta({ notNull: true }),
        name: z.string().meta({ notNull: true }),
        is_dm: z.boolean().meta({ notNull: true, default: false }),
        workspace_path: z.string().nullable(),
        artifact_review: z.boolean().meta({ notNull: true, default: false }),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
        updated_at: z.date().meta({ notNull: true, default: 'now' }),
      },
    },
    {
      name: 'department_members',
      columns: {
        department_id: z.uuid().meta({ notNull: true, references: 'departments', onDelete: 'CASCADE' }),
        agent_id: z.uuid().meta({ notNull: true, references: 'agents', onDelete: 'CASCADE' }),
        role: z.string().meta({ notNull: true, default: "member" }),
        joined_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      uniques: [["department_id","agent_id"]],
      indexes: [
        { cols: ['agent_id'], name: 'idx_dm_agent' },
      ],
    },
    {
      name: 'messages',
      columns: {
        id: f.pk(z.uuid()),
        department_id: z.uuid().meta({ notNull: true, references: 'departments', onDelete: 'CASCADE' }),
        sender_id: z.uuid().meta({ notNull: true, references: 'agents', onDelete: 'CASCADE' }),
        content: z.string().meta({ notNull: true }),
        msg_type: z.string().meta({ notNull: true, default: "text" }),
        ai_draft: z.string().nullable(),
        ai_approved: z.boolean().nullable(),
        ai_step: z.json().nullable(),
        reply_to: z.uuid().meta({ references: 'messages', onDelete: 'SET NULL' }).nullable(),
        attachments: z.json().nullable(),
        routed_to: z.string().nullable(),
        feedback: z.string().nullable(),
        quick_replies: z.json().nullable(),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      indexes: [
        { cols: ['department_id', 'created_at'], name: 'idx_messages_department' },
      ],
    },
    {
      name: 'kb_documents',
      columns: {
        id: f.pk(z.uuid()),
        agent_id: z.uuid().meta({ notNull: true, references: 'agents', onDelete: 'CASCADE' }),
        filename: z.string().meta({ notNull: true }),
        content: z.string().meta({ notNull: true }),
        chunk_count: z.number().int().meta({ notNull: true, default: 0 }),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      indexes: [
        { cols: ['agent_id'], name: 'idx_kb_agent' },
      ],
    },
    {
      name: 'agent_logs',
      columns: {
        id: f.pk(z.uuid()),
        agent_id: z.uuid().meta({ notNull: true, references: 'agents', onDelete: 'CASCADE' }),
        app_id: z.uuid().meta({ notNull: true }),
        department_id: z.uuid().meta({ references: 'departments', onDelete: 'SET NULL' }).nullable(),
        messages_count: z.number().int().meta({ notNull: true, default: 0 }),
        steps_count: z.number().int().meta({ notNull: true, default: 0 }),
        tokens_prompt: z.number().int().meta({ notNull: true, default: 0 }),
        tokens_completion: z.number().int().meta({ notNull: true, default: 0 }),
        tokens_total: z.number().int().meta({ notNull: true, default: 0 }),
        elapsed_ms: z.number().int().meta({ notNull: true, default: 0 }),
        success: z.boolean().meta({ notNull: true, default: true }),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      indexes: [
        { cols: ['agent_id', { col: 'created_at', desc: true }], name: 'idx_agent_logs_agent' },
        { cols: ['app_id', { col: 'created_at', desc: true }], name: 'idx_agent_logs_app' },
      ],
    },
    {
      name: 'agent_runs',
      columns: {
        id: f.pk(z.uuid()),
        app_id: z.uuid().meta({ notNull: true }),
        department_id: z.uuid().meta({ references: 'departments', onDelete: 'SET NULL' }).nullable(),
        orchestrator_id: z.uuid().meta({ references: 'agents', onDelete: 'CASCADE' }).nullable(),
        parent_run_id: z.uuid().meta({ references: 'agent_runs', onDelete: 'CASCADE' }).nullable(),
        kind: z.string().meta({ notNull: true, default: "orchestration" }),
        plan_json: z.json().nullable(),
        worker_results: z.json().nullable(),
        status: z.string().meta({ notNull: true, default: "planned" }),
        request_id: z.string().nullable(),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
        updated_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      indexes: [
        { cols: ['app_id', { col: 'created_at', desc: true }], name: 'idx_agent_runs_app' },
        { cols: ['parent_run_id'], name: 'idx_agent_runs_parent' },
      ],
    },
    {
      name: 'webhook_logs',
      columns: {
        id: f.pk(z.uuid()),
        agent_id: z.uuid().meta({ notNull: true, references: 'agents', onDelete: 'CASCADE' }),
        app_id: z.uuid().meta({ notNull: true }),
        request_body: z.string().nullable(),
        response_body: z.string().nullable(),
        response_status: z.number().int().nullable(),
        elapsed_ms: z.number().int().meta({ notNull: true, default: 0 }),
        success: z.boolean().meta({ notNull: true, default: true }),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      indexes: [
        { cols: ['agent_id', { col: 'created_at', desc: true }], name: 'idx_webhook_logs_agent' },
      ],
    },
    {
      name: 'webhook_conversations',
      columns: {
        id: f.pk(z.uuid()),
        agent_id: z.uuid().meta({ notNull: true, references: 'agents', onDelete: 'CASCADE' }),
        conversation_id: z.string().meta({ notNull: true }),
        role: z.string().meta({ notNull: true }),
        content: z.string().meta({ notNull: true }),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      indexes: [
        { cols: ['agent_id', 'conversation_id', 'created_at'], name: 'idx_webhook_conv' },
      ],
    },
    {
      name: 'kb_chunks',
      columns: {
        id: f.pk(z.uuid()),
        document_id: z.uuid().meta({ notNull: true, references: 'kb_documents', onDelete: 'CASCADE' }),
        agent_id: z.uuid().meta({ notNull: true, references: 'agents', onDelete: 'CASCADE' }),
        content: z.string().meta({ notNull: true }),
        chunk_index: z.number().int().meta({ notNull: true }),
        embedding: z.vector(1024).nullable(), // W4: S2 单源——vector 语义（Infer=number[]）——columnTypes vector(1024) 真库特化
        created_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      columnTypes: {
        embedding: 'vector(1024)',
      },
      indexes: [
        { cols: ['agent_id'], name: 'idx_kb_chunks_agent' },
        { cols: ['embedding'], name: 'idx_kb_chunks_embedding', using: 'ivfflat', opclass: 'vector_cosine_ops', with: 'lists = 100' },
      ],
    },
    {
      name: 'agent_skills',
      columns: {
        id: f.pk(z.uuid()),
        agent_id: z.uuid().meta({ notNull: true, references: 'agents', onDelete: 'CASCADE' }),
        skill_name: z.string().meta({ notNull: true }),
        skill_dir: z.string().meta({ notNull: true }),
        enabled: z.boolean().meta({ notNull: true, default: true }),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      uniques: [["agent_id","skill_name"]],
      indexes: [
        { cols: ['agent_id'], name: 'idx_agent_skills_agent' },
      ],
    },
    {
      name: 'role_templates',
      columns: {
        id: f.pk(z.uuid()),
        name: z.string().meta({ notNull: true }),
        slug: z.string().meta({ notNull: true, unique: true }),
        description: z.string().nullable(),
        icon: z.string().nullable(),
        category: z.string().meta({ notNull: true, default: "general" }),
        default_system_prompt: z.string().nullable(),
        default_model: z.string().nullable(),
        default_temperature: z.number().meta({ default: 0.7 }).nullable(),
        default_max_tokens: z.number().int().meta({ default: 2048 }).nullable(),
        default_allow_file_tools: z.boolean().meta({ default: false }).nullable(),
        default_allow_command_exec: z.boolean().meta({ default: false }).nullable(),
        default_workspace_hint: z.string().nullable(),
        default_skills: z.json().meta({ default: "[]" }).nullable(),
        sort_order: z.number().int().meta({ default: 0 }).nullable(),
        is_active: z.boolean().meta({ notNull: true, default: true }),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
      },
    },
    {
      name: 'events',
      columns: {
        id: f.pk(z.uuid()),
        app_id: z.uuid().meta({ notNull: true }),
        event: z.string().meta({ notNull: true }),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      indexes: [
        { cols: ['app_id', 'event'], name: 'idx_events_app' },
        { cols: ['event', { col: 'created_at', desc: true }], name: 'idx_events_event' },
        { cols: ['app_id', 'event'], name: 'uq_events_first_message', unique: true, where: [{ col: 'event', eq: 'first_message' }] },
      ],
    },
    {
      name: 'audit_logs',
      columns: {
        id: f.pk(z.uuid()),
        app_id: z.uuid().meta({ notNull: true }),
        user_id: z.uuid().nullable(),
        action: z.string().meta({ notNull: true }),
        target_type: z.string().nullable(),
        target_id: z.uuid().nullable(),
        detail: z.json().nullable(),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      indexes: [
        { cols: ['app_id', { col: 'created_at', desc: true }], name: 'idx_audit_logs_app' },
      ],
    },
    {
      name: 'agent_versions',
      columns: {
        id: f.pk(z.uuid()),
        agent_id: z.uuid().meta({ notNull: true, references: 'agents', onDelete: 'CASCADE' }),
        app_id: z.uuid().meta({ notNull: true }),
        version: z.number().int().meta({ notNull: true }),
        snapshot: z.json().meta({ notNull: true }),
        note: z.string().nullable(),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      uniques: [["agent_id","version"]],
      indexes: [
        { cols: ['agent_id', { col: 'version', desc: true }], name: 'idx_agent_versions_agent' },
      ],
    },
    {
      name: 'group_memories',
      columns: {
        department_id: f.pk(z.uuid()),
        summary: z.string().nullable(),
        msg_count: z.number().int().meta({ notNull: true, default: 0 }),
        updated_at: z.date().meta({ notNull: true, default: 'now' }),
      },
    },
    {
      name: 'answer_cache',
      columns: {
        id: f.pk(z.uuid()),
        app_id: z.uuid().meta({ notNull: true }),
        question: z.string().meta({ notNull: true }),
        answer: z.string().meta({ notNull: true }),
        hits: z.number().int().meta({ notNull: true, default: 0 }),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
        updated_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      indexes: [
        { cols: ['app_id'], name: 'idx_answer_cache_app' },
      ],
    },
    {
      name: 'skill_ratings',
      columns: {
        id: f.pk(z.uuid()),
        skill_dir: z.string().meta({ notNull: true }),
        app_id: z.uuid().meta({ notNull: true }),
        liked: z.boolean().meta({ notNull: true }),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      uniques: [["skill_dir","app_id"]],
      indexes: [
        { cols: ['skill_dir'], name: 'idx_skill_ratings_dir' },
      ],
    },
    {
      name: 'video_tasks',
      columns: {
        id: f.pk(z.uuid()),
        app_id: z.uuid().meta({ notNull: true }),
        department_id: z.uuid().nullable(),
        agent_id: z.uuid().nullable(),
        task_id: z.string().meta({ notNull: true }),
        prompt: z.string().meta({ notNull: true }),
        status: z.string().meta({ notNull: true, default: 'pending' }),
        filename: z.string().meta({ notNull: true }),
        path: z.string().nullable(),
        error: z.string().nullable(),
        params: z.json().nullable(),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
        updated_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      indexes: [
        { cols: ['task_id'], name: 'idx_video_tasks_task' },
      ],
    },
    {
      name: 'agent_run_states',
      columns: {
        message_id: f.pk(z.uuid()),
        agent_id: z.uuid().meta({ notNull: true }),
        department_id: z.uuid().meta({ notNull: true }),
        app_id: z.uuid().meta({ notNull: true }),
        steps: z.json().meta({ notNull: true, default: "[]" }),
        status: z.string().meta({ notNull: true, default: "running" }),
        updated_at: z.date().meta({ notNull: true, default: 'now' }),
      },
    },
    {
      name: 'sandboxes',
      columns: {
        id: f.pk(z.uuid()),
        app_id: z.uuid().meta({ notNull: true }),
        department_id: z.uuid().nullable(),
        name: z.string().meta({ notNull: true }),
        status: z.string().meta({ notNull: true, default: "requested" }),
        mode: z.string().meta({ notNull: true, default: "persistent" }),
        image: z.string().meta({ notNull: true, default: "ap-sandbox:latest" }),
        network: z.boolean().meta({ notNull: true, default: true }),
        memory_mb: z.number().int().meta({ notNull: true, default: 1024 }),
        cpus: z.number().int().meta({ notNull: true, default: 1 }),
        error: z.string().nullable(),
        workspace: z.string().nullable(),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
        last_used_at: z.date().nullable(),
        expires_at: z.date().nullable(),
        terminated_at: z.date().nullable(),
        updated_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      indexes: [
        { cols: ['department_id'], name: 'idx_sandboxes_dept' },
        { cols: ['status', 'last_used_at'], name: 'idx_sandboxes_status' },
        { cols: ['department_id'], name: 'idx_sandboxes_dept_active', unique: true, where: [{ col: 'department_id', isNull: false }, { col: 'status', ne: 'terminated' }] },
      ],
    },
    {
      name: 'sandbox_events',
      columns: {
        id: f.pk(z.number().int()),
        sandbox_id: z.uuid().meta({ notNull: true }),
        app_id: z.uuid().nullable(),
        type: z.string().meta({ notNull: true }),
        detail: z.string().nullable(),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      columnTypes: {
        id: 'BIGSERIAL',
      },
      indexes: [
        { cols: ['sandbox_id', { col: 'created_at', desc: true }], name: 'idx_sandbox_events_sb' },
      ],
    },
    {
      name: 'survey_campaigns',
      columns: {
        id: f.pk(z.uuid()),
        app_id: z.uuid().meta({ notNull: true }),
        total: z.number().int().meta({ notNull: true }),
        concurrency: z.number().int().meta({ notNull: true }),
        url: z.string().meta({ notNull: true, default: "" }),
        retry: z.number().int().meta({ notNull: true, default: 2 }),
        status: z.string().meta({ notNull: true, default: "running" }),
        completed: z.number().int().meta({ notNull: true, default: 0 }),
        failed: z.number().int().meta({ notNull: true, default: 0 }),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
        updated_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      indexes: [
        { cols: ['app_id', { col: 'created_at', desc: true }], name: 'idx_survey_campaigns_app' },
      ],
    },
    {
      name: 'survey_campaign_runs',
      columns: {
        id: f.pk(z.uuid()),
        campaign_id: z.uuid().meta({ notNull: true, references: 'survey_campaigns', onDelete: 'CASCADE' }),
        agent_id: z.uuid().meta({ notNull: true }),
        agent_name: z.string().meta({ notNull: true }),
        dept_id: z.uuid().meta({ notNull: true }),
        status: z.string().meta({ notNull: true, default: "queued" }),
        attempts: z.number().int().meta({ notNull: true, default: 0 }),
        started_at: z.date().nullable(),
        finished_at: z.date().nullable(),
        error: z.string().nullable(),
      },
      indexes: [
        { cols: ['campaign_id', 'status'], name: 'idx_survey_runs_campaign' },
      ],
    },
    {
      name: 'video_tasks',
      columns: {
        id: f.pk(z.uuid()),
        app_id: z.uuid().meta({ notNull: true }),
        department_id: z.uuid().nullable(),
        agent_id: z.uuid().nullable(),
        task_id: z.string().meta({ notNull: true }),
        prompt: z.string().meta({ notNull: true }),
        status: z.string().meta({ notNull: true, default: "pending" }),
        filename: z.string().meta({ notNull: true }),
        path: z.string().nullable(),
        error: z.string().nullable(),
        params: z.json().nullable(),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
        updated_at: z.date().meta({ notNull: true, default: 'now' }),
      },
      indexes: [
        { cols: ['task_id'], name: 'idx_video_tasks_task' },
      ],
    },
    {
      name: 'survey_submissions',
      columns: {
        id: f.pk(z.string()),
        source: z.string().meta({ notNull: true }),
        age: z.string().nullable(),
        industry: z.string().nullable(),
        rating: z.number().int().nullable(),
        focus: z.json().nullable(),
        feedback: z.string().nullable(),
        submitted_at: z.date().meta({ notNull: true, default: 'now' }),
        campaign_id: z.string().nullable(),
      },
    },
    {
      name: 'survey_answers',
      columns: {
        id: f.pk(z.number().int()),
        source: z.string().meta({ notNull: true }),
        question: z.string().nullable(),
        answer: z.string().nullable(),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
        campaign_id: z.string().nullable(),
      },
      columnTypes: { id: 'BIGSERIAL' },
    },
    {
      name: 'agent_memories',
      columns: {
        agent_id: f.pk(z.uuid()).meta({ references: 'agents', onDelete: 'cascade' }),
        content: z.string().meta({ notNull: true }),
        updated_at: z.date().meta({ notNull: true, default: 'now' }),
      },
    },
    {
      name: 'enterprises',
      columns: {
        id: f.pk(z.uuid()),
        name: z.string().meta({ notNull: true }),
        owner_user_id: z.uuid().nullable(),
        created_at: z.date().meta({ notNull: true, default: 'now' }),
      },
    },
    {
      name: 'app_ai_configs',
      columns: {
        app_id: f.pk(z.uuid()),
        base_url: z.string().nullable(),
        api_key: z.string().nullable(),
        model: z.string().nullable(),
        updated_at: z.date().meta({ notNull: true, default: 'now' }),
      },
    },
  ],
}

/** 框架 _weifuwu_apps 平台扩展列（商业化/沙盒配额/企业归属）——声明式增量：
 *  新库在 weifuwu-users 建表后补列；老库 ADD COLUMN IF NOT EXISTS 幂等（无 ALTER 文本） */
export const APP_EXT_SCHEMA: import('weifuwu').SchemaModule = {
  tables: [
    {
      name: '_weifuwu_apps',
      columns: {
        status: z.string().meta({ notNull: true, default: 'active' }),
        plan: z.string().meta({ notNull: true, default: 'free' }),
        trial_ends_at: z.date().nullable(),
        monthly_token_limit: z.number().int().meta({ notNull: true, default: 50000 }),
        sandbox_quota: z.number().int().meta({ notNull: true, default: 5 }),
        enterprise_id: z.uuid().nullable(),
      },
    },
  ],
}
