/**
 * 组件冒烟陈列——第一批（40 核心组件——表单/浮层/交互类）
 *
 * 冒烟基线：全部渲染 + 点击扫描（console.error 零——渲染/交互不崩）。
 * 每个组件带 data-smoke 标记（e2e 断言渲染 + 点击定位）。
 * 深度行为断言在各自场景（后续分批）。
 */
import { h, type VNode } from '../../../client/vdom/index.ts'
import type { Component } from '../../../client/vdom/index.ts'
import {
  Button, Input, Textarea, SearchInput, PasswordInput, InputNumber, Select, Switch,
  Checkbox, CheckboxGroup, RadioGroup, Slider, Rate, PinInput, TagsInput, Tabs,
  Menu, Collapse, Accordion, Carousel, Pagination, Table, List, Tag, Badge, Avatar,
  StatCard, ProgressBar, Alert, EmptyState, Divider, Space, Text, Grid, Steps,
  Timeline, Breadcrumb, Calendar, DatePicker, Cascader,
  AutoComplete, Affix, AvatarGroup, BackTop, Card, ColorPicker, ContextMenu,
  CopyButton, Descriptions, Drawer, Dropdown, Field, FilePreview, FileUpload,
  FloatButton, Form, HoverCard, Icon, Img, InfiniteScroll, InView, JSONViewer,
  Kanban, Label, Layout, Link, Loading, Markdown, Mentions, Menubar,
  MessageBubble, Modal, NavMenu, Notification, PageHeader, Pipeline, Popconfirm,
  Popover, QRCode, Resizable, Result, Scrollbar, SegmentedControl, SessionList,
  Skeleton, SortableList, Sparkline, TabBar, ThemeSwitch, ToggleGroup, Tooltip,
  Tour, Transfer, Tree, TreeSelect, VirtualList, VirtualTable,
  AlertGroup, Anchor, AspectRatio, ApprovalCard, CodeBlock, DiffView, ExportCSV,
  Highlight, LogViewer, PromptTemplate, ReasoningBlock, ToolCallCard,
  Watermark, Wave, ActionSheet, AuthPage, ChatInput, CitationCard, CodeEditor,
  Editor, MarkdownEditor, AiChat, ImageCropper, VideoPlayer,
} from '../../../client/components/index.ts'

/** 陈列项（组件名 → 简单实例化——渲染不崩为基线） */
export interface SmokeItem {
  name: string
  vnode: () => VNode
}

const btn = (name: string, children: string) =>
  h('button', { class: `smoke-click-${name}`, onClick: () => {} }, children)

export const smokeItems: SmokeItem[] = [
  { name: 'Button', vnode: () => h('div', { class: 'smoke-Button' }, [h(Button, {}, '按钮'), h(Button, { variant: 'primary' }, '主按钮'), h(Button, { size: 'sm' }, '小')]) },
  { name: 'Input', vnode: () => h('div', { class: 'smoke-Input' }, h(Input, { placeholder: '输入' })) },
  { name: 'Textarea', vnode: () => h('div', { class: 'smoke-Textarea' }, h(Textarea, { placeholder: '多行' })) },
  { name: 'SearchInput', vnode: () => h('div', { class: 'smoke-SearchInput' }, h(SearchInput, { placeholder: '搜索' })) },
  { name: 'PasswordInput', vnode: () => h('div', { class: 'smoke-PasswordInput' }, h(PasswordInput, { placeholder: '密码' })) },
  { name: 'InputNumber', vnode: () => h('div', { class: 'smoke-InputNumber' }, h(InputNumber, { defaultValue: 5 })) },
  { name: 'Select', vnode: () => h('div', { class: 'smoke-Select' }, h(Select, { options: [{ value: 'a', label: 'A' }, { value: 'b', label: 'B' }], placeholder: '选择' })) },
  { name: 'Switch', vnode: () => h('div', { class: 'smoke-Switch' }, h(Switch, { defaultChecked: true })) },
  { name: 'Checkbox', vnode: () => h('div', { class: 'smoke-Checkbox' }, h(Checkbox, { checked: true }, '勾选')) },
  { name: 'CheckboxGroup', vnode: () => h('div', { class: 'smoke-CheckboxGroup' }, h(CheckboxGroup, { options: ['A', 'B', 'C'] })) },
  { name: 'RadioGroup', vnode: () => h('div', { class: 'smoke-RadioGroup' }, h(RadioGroup, { options: ['甲', '乙'] })) },
  { name: 'Slider', vnode: () => h('div', { class: 'smoke-Slider' }, h(Slider, { defaultValue: 30 })) },
  { name: 'Rate', vnode: () => h('div', { class: 'smoke-Rate' }, h(Rate, { defaultValue: 3 })) },
  { name: 'PinInput', vnode: () => h('div', { class: 'smoke-PinInput' }, h(PinInput, { length: 4 })) },
  { name: 'TagsInput', vnode: () => h('div', { class: 'smoke-TagsInput' }, h(TagsInput, { defaultValue: ['a', 'b'] })) },
  { name: 'Tabs', vnode: () => h('div', { class: 'smoke-Tabs' }, h(Tabs, { items: [{ key: '1', label: '标签1' }, { key: '2', label: '标签2' }] })) },
  { name: 'Menu', vnode: () => h('div', { class: 'smoke-Menu' }, h(Menu, { items: [{ key: '1', label: '菜单1' }, { key: '2', label: '菜单2' }] })) },
  { name: 'Collapse', vnode: () => h('div', { class: 'smoke-Collapse' }, h(Collapse, { items: [{ key: '1', title: '面板1', content: '内容1' }] })) },
  { name: 'Accordion', vnode: () => h('div', { class: 'smoke-Accordion' }, h(Accordion, { items: [{ key: '1', title: '折叠1', content: '内容1' }] })) },
  { name: 'Carousel', vnode: () => h('div', { class: 'smoke-Carousel' }, h(Carousel, { items: ['图1', '图2'] })) },
  { name: 'Pagination', vnode: () => h('div', { class: 'smoke-Pagination' }, h(Pagination, { total: 50, pageSize: 10 })) },
  { name: 'Table', vnode: () => h('div', { class: 'smoke-Table' }, h(Table, { columns: [{ key: 'name', title: '名称' }], data: [{ name: '行1' }] })) },
  { name: 'List', vnode: () => h('div', { class: 'smoke-List' }, h(List, { items: ['项1', '项2'], renderItem: (i: string) => h('div', {}, i) })) },
  { name: 'Tag', vnode: () => h('div', { class: 'smoke-Tag' }, h(Tag, { color: 'blue' }, '标签')) },
  { name: 'Badge', vnode: () => h('div', { class: 'smoke-Badge' }, h(Badge, { count: 5 }, '消息')) },
  { name: 'Avatar', vnode: () => h('div', { class: 'smoke-Avatar' }, h(Avatar, { name: '张三' })) },
  { name: 'StatCard', vnode: () => h('div', { class: 'smoke-StatCard' }, h(StatCard, { title: '订单', value: '128' })) },
  { name: 'ProgressBar', vnode: () => h('div', { class: 'smoke-ProgressBar' }, h(ProgressBar, { percent: 60 })) },
  { name: 'Alert', vnode: () => h('div', { class: 'smoke-Alert' }, h(Alert, { type: 'success', title: '成功' })) },
  { name: 'EmptyState', vnode: () => h('div', { class: 'smoke-EmptyState' }, h(EmptyState, { description: '无数据' })) },
  { name: 'Divider', vnode: () => h('div', { class: 'smoke-Divider' }, h(Divider, {}, '分隔')) },
  { name: 'Space', vnode: () => h('div', { class: 'smoke-Space' }, h(Space, {}, [h(Button, {}, 'a'), h(Button, {}, 'b')])) },
  { name: 'Typography', vnode: () => h('div', { class: 'smoke-Typography' }, h(Text, {}, '文本')) },
  { name: 'Grid', vnode: () => h('div', { class: 'smoke-Grid' }, h(Grid, { cols: 2 }, [h('div', {}, '格1'), h('div', {}, '格2')])) },
  { name: 'Steps', vnode: () => h('div', { class: 'smoke-Steps' }, h(Steps, { items: [{ title: '一步' }, { title: '二步' }], current: 0 })) },
  { name: 'AutoComplete', vnode: () => h('div', { class: 'smoke-AutoComplete' }, h(AutoComplete, { options: [{ value: '苹果' }, { value: '香蕉' }], placeholder: '联想' })) },
  { name: 'Affix', vnode: () => h('div', { class: 'smoke-Affix' }, h(Affix, {}, '吸顶')) },
  { name: 'AvatarGroup', vnode: () => h('div', { class: 'smoke-AvatarGroup' }, h(AvatarGroup, { users: [{ name: '甲' }, { name: '乙' }] })) },
  { name: 'BackTop', vnode: () => h('div', { class: 'smoke-BackTop' }, h(BackTop, {})) },
  { name: 'Card', vnode: () => h('div', { class: 'smoke-Card' }, h(Card, { title: '卡片' }, '内容')) },
  { name: 'ColorPicker', vnode: () => h('div', { class: 'smoke-ColorPicker' }, h(ColorPicker, { defaultValue: '#1677ff' })) },
  { name: 'ContextMenu', vnode: () => h('div', { class: 'smoke-ContextMenu' }, h(ContextMenu, { menu: [{ key: '1', label: '删除' }] }, '右键')) },
  { name: 'CopyButton', vnode: () => h('div', { class: 'smoke-CopyButton' }, h(CopyButton, { text: '复制我' })) },
  { name: 'Descriptions', vnode: () => h('div', { class: 'smoke-Descriptions' }, h(Descriptions, { items: [{ label: '名称', value: '值' }] })) },
  { name: 'Drawer', vnode: () => h('div', { class: 'smoke-Drawer' }, h(Drawer, { open: false, title: '抽屉' }, '内容')) },
  { name: 'Dropdown', vnode: () => h('div', { class: 'smoke-Dropdown' }, h(Dropdown, { menu: [{ key: '1', label: '项1' }] }, '下拉')) },
  { name: 'Field', vnode: () => h('div', { class: 'smoke-Field' }, h(Field, { label: '字段' }, '值')) },
  { name: 'FilePreview', vnode: () => h('div', { class: 'smoke-FilePreview' }, h(FilePreview, { name: '文档.pdf', url: '' })) },
  { name: 'FileUpload', vnode: () => h('div', { class: 'smoke-FileUpload' }, h(FileUpload, {})) },
  { name: 'FloatButton', vnode: () => h('div', { class: 'smoke-FloatButton' }, h(FloatButton, {})) },
  { name: 'Form', vnode: () => h('div', { class: 'smoke-Form' }, h(Form, {}, h(Field, { name: 'a' }, h(Input, { name: 'a' })))) },
  { name: 'HoverCard', vnode: () => h('div', { class: 'smoke-HoverCard' }, h(HoverCard, { content: '提示' }, '悬停')) },
  { name: 'Icon', vnode: () => h('div', { class: 'smoke-Icon' }, h(Icon, { name: 'check' })) },
  { name: 'Img', vnode: () => h('div', { class: 'smoke-Img' }, h(Img, { src: '', alt: '图' })) },
  { name: 'InfiniteScroll', vnode: () => h('div', { class: 'smoke-InfiniteScroll' }, h(InfiniteScroll, { hasMore: false, loadMore: async () => {} }, '内容')) },
  { name: 'InView', vnode: () => h('div', { class: 'smoke-InView' }, h(InView, {}, '可见')) },
  { name: 'JSONViewer', vnode: () => h('div', { class: 'smoke-JSONViewer' }, h(JSONViewer, { data: { a: 1 } })) },
  { name: 'Kanban', vnode: () => h('div', { class: 'smoke-Kanban' }, h(Kanban, { columns: [{ id: 'c1', title: '列1', items: [{ id: 'k1', title: '卡1' }] }], onMove: () => {} })) },
  { name: 'Label', vnode: () => h('div', { class: 'smoke-Label' }, h(Label, {}, '标签文本')) },
  { name: 'Layout', vnode: () => h('div', { class: 'smoke-Layout' }, h(Layout, { header: '顶', aside: '侧' }, '内容')) },
  { name: 'Link', vnode: () => h('div', { class: 'smoke-Link' }, h(Link, { href: '#', children: '链接' })) },
  { name: 'Loading', vnode: () => h('div', { class: 'smoke-Loading' }, h(Loading, {})) },
  { name: 'Markdown', vnode: () => h('div', { class: 'smoke-Markdown' }, h(Markdown, { content: '# 标题\n内容' })) },
  { name: 'Mentions', vnode: () => h('div', { class: 'smoke-Mentions' }, h(Mentions, { options: [{ value: '张三' }], placeholder: '@' })) },
  { name: 'Menubar', vnode: () => h('div', { class: 'smoke-Menubar' }, h(Menubar, { items: [{ key: '1', label: '文件' }] })) },
  { name: 'MessageBubble', vnode: () => h('div', { class: 'smoke-MessageBubble' }, h(MessageBubble, { role: 'user' }, '消息')) },
  { name: 'Modal', vnode: () => h('div', { class: 'smoke-Modal' }, h(Modal, { open: false, title: '弹窗' }, '内容')) },
  { name: 'NavMenu', vnode: () => h('div', { class: 'smoke-NavMenu' }, h(NavMenu, { items: [{ key: '1', label: '导航1' }] })) },
  { name: 'Notification', vnode: () => h('div', { class: 'smoke-Notification' }, h(Notification, {})) },
  { name: 'PageHeader', vnode: () => h('div', { class: 'smoke-PageHeader' }, h(PageHeader, { title: '页面标题' })) },
  { name: 'Pipeline', vnode: () => h('div', { class: 'smoke-Pipeline' }, h(Pipeline, { nodes: [{ id: 'n1', label: '一' }, { id: 'n2', label: '二' }], edges: [{ from: 'n1', to: 'n2' }] })) },
  { name: 'Popconfirm', vnode: () => h('div', { class: 'smoke-Popconfirm' }, h(Popconfirm, { title: '确认？' }, '删除')) },
  { name: 'Popover', vnode: () => h('div', { class: 'smoke-Popover' }, h(Popover, { content: '气泡' }, '悬浮')) },
  { name: 'QRCode', vnode: () => h('div', { class: 'smoke-QRCode' }, h(QRCode, { value: 'https://x.com' })) },
  { name: 'Resizable', vnode: () => h('div', { class: 'smoke-Resizable' }, h(Resizable, {}, '可拖')) },
  { name: 'Result', vnode: () => h('div', { class: 'smoke-Result' }, h(Result, { status: 'success', title: '成功' })) },
  { name: 'Scrollbar', vnode: () => h('div', { class: 'smoke-Scrollbar' }, h(Scrollbar, { style: { height: '50px' } }, '滚动')) },
  { name: 'SegmentedControl', vnode: () => h('div', { class: 'smoke-SegmentedControl' }, h(SegmentedControl, { options: ['日', '周', '月'] })) },
  { name: 'SessionList', vnode: () => h('div', { class: 'smoke-SessionList' }, h(SessionList, { sessions: [{ id: 's1', title: '会话1' }] })) },
  { name: 'Skeleton', vnode: () => h('div', { class: 'smoke-Skeleton' }, h(Skeleton, {})) },
  { name: 'SortableList', vnode: () => h('div', { class: 'smoke-SortableList' }, h(SortableList, { items: ['a', 'b'], renderItem: (i: string) => h('div', {}, i) })) },
  { name: 'Sparkline', vnode: () => h('div', { class: 'smoke-Sparkline' }, h(Sparkline, { data: [1, 3, 2, 5] })) },
  { name: 'TabBar', vnode: () => h('div', { class: 'smoke-TabBar' }, h(TabBar, { items: [{ key: '1', title: '首页' }, { key: '2', title: '我的' }] })) },
  { name: 'ThemeSwitch', vnode: () => h('div', { class: 'smoke-ThemeSwitch' }, h(ThemeSwitch, {})) },
  { name: 'ToggleGroup', vnode: () => h('div', { class: 'smoke-ToggleGroup' }, h(ToggleGroup, { options: ['A', 'B'] })) },
  { name: 'Tooltip', vnode: () => h('div', { class: 'smoke-Tooltip' }, h(Tooltip, { content: '提示' }, '悬浮')) },
  { name: 'Tour', vnode: () => h('div', { class: 'smoke-Tour' }, h(Tour, { steps: [{ title: '步骤1' }], open: false })) },
  { name: 'Transfer', vnode: () => h('div', { class: 'smoke-Transfer' }, h(Transfer, { data: [{ key: '1', title: '项1' }] })) },
  { name: 'Tree', vnode: () => h('div', { class: 'smoke-Tree' }, h(Tree, { treeData: [{ key: '1', title: '节点1' }] })) },
  { name: 'TreeSelect', vnode: () => h('div', { class: 'smoke-TreeSelect' }, h(TreeSelect, { treeData: [{ value: '1', label: '节点1' }], placeholder: '选树' })) },
  { name: 'VirtualList', vnode: () => h('div', { class: 'smoke-VirtualList' }, h(VirtualList, { items: Array.from({ length: 50 }, (_, i) => `行${i}`), height: 100, itemHeight: 20, renderItem: (i: string) => h('div', {}, i) })) },
  { name: 'VirtualTable', vnode: () => h('div', { class: 'smoke-VirtualTable' }, h(VirtualTable, { columns: [{ key: 'a', title: 'A' }], data: [{ a: '1' }], height: 100 })) },
  { name: 'AlertGroup', vnode: () => h('div', { class: 'smoke-AlertGroup' }, h(AlertGroup, { items: [{ type: 'success', title: '成功' }, { type: 'info', title: '提示' }] })) },
  { name: 'Anchor', vnode: () => h('div', { class: 'smoke-Anchor' }, h(Anchor, { items: [{ key: 's1', title: '节1', href: '#s1' }] })) },
  { name: 'AspectRatio', vnode: () => h('div', { class: 'smoke-AspectRatio' }, h(AspectRatio, { ratio: 16 / 9 }, '内容')) },
  { name: 'ApprovalCard', vnode: () => h('div', { class: 'smoke-ApprovalCard' }, h(ApprovalCard, { request: { id: 'a1', toolName: '查询', args: {}, status: 'pending' } })) },
  { name: 'CodeBlock', vnode: () => h('div', { class: 'smoke-CodeBlock' }, h(CodeBlock, { code: 'const a = 1', language: 'ts' })) },
  { name: 'DiffView', vnode: () => h('div', { class: 'smoke-DiffView' }, h(DiffView, { oldText: '旧', newText: '新' })) },
  { name: 'ExportCSV', vnode: () => h('div', { class: 'smoke-ExportCSV' }, h(ExportCSV, { data: [{ a: 1 }], filename: 'x.csv' }, '导出')) },
  { name: 'Highlight', vnode: () => h('div', { class: 'smoke-Highlight' }, h(Highlight, { text: '高亮文本', query: '高亮' })) },
  { name: 'LogViewer', vnode: () => h('div', { class: 'smoke-LogViewer' }, h(LogViewer, { lines: ['info 日志1', 'error 日志2'] })) },
  { name: 'PromptTemplate', vnode: () => h('div', { class: 'smoke-PromptTemplate' }, h(PromptTemplate, { template: '你好 {name}', variables: { name: '张三' } })) },
  { name: 'ReasoningBlock', vnode: () => h('div', { class: 'smoke-ReasoningBlock' }, h(ReasoningBlock, { content: '思考过程' })) },
  { name: 'ToolCallCard', vnode: () => h('div', { class: 'smoke-ToolCallCard' }, h(ToolCallCard, { call: { id: 't1', name: '查询', args: {} } })) },
  { name: 'Watermark', vnode: () => h('div', { class: 'smoke-Watermark' }, h(Watermark, { text: '水印' }, '内容')) },
  { name: 'Wave', vnode: () => h('div', { class: 'smoke-Wave' }, h(Wave, {}, '波纹')) },
  { name: 'ActionSheet', vnode: () => h('div', { class: 'smoke-ActionSheet' }, h(ActionSheet, { open: false, items: [{ key: '1', label: '选项1' }] })) },
  { name: 'AuthPage', vnode: () => h('div', { class: 'smoke-AuthPage' }, h(AuthPage, {})) },
  { name: 'ChatInput', vnode: () => h('div', { class: 'smoke-ChatInput' }, h(ChatInput, {})) },
  { name: 'CitationCard', vnode: () => h('div', { class: 'smoke-CitationCard' }, h(CitationCard, { source: '文档A', snippet: '引用内容' })) },
  { name: 'CodeEditor', vnode: () => h('div', { class: 'smoke-CodeEditor' }, h(CodeEditor, { value: 'const a = 1', language: 'ts' })) },
  { name: 'Editor', vnode: () => h('div', { class: 'smoke-Editor' }, h(Editor, { value: '文本' })) },
  { name: 'MarkdownEditor', vnode: () => h('div', { class: 'smoke-MarkdownEditor' }, h(MarkdownEditor, { value: '# 标题' })) },
  { name: 'AiChat', vnode: () => h('div', { class: 'smoke-AiChat' }, h(AiChat, { chat: {} as never })) },
  { name: 'ImageCropper', vnode: () => h('div', { class: 'smoke-ImageCropper' }, h(ImageCropper, { src: 'data:image/gif;base64,R0lGODlhAQABAAAAACw=' })) },
  { name: 'VideoPlayer', vnode: () => h('div', { class: 'smoke-VideoPlayer' }, h(VideoPlayer, { src: 'https://example.com/v.mp4' })) },
]

/** 冒烟陈列场景（全部渲染——data-smoke 标记） */
export const SmokeScene: Component = () => {
  // 冒烟项数（e2e 断言——window 挂载——客户端执行）
  ;(window as unknown as { __smokeCount?: number }).__smokeCount = smokeItems.length
  return () =>
    h('div', { class: 'smoke-gallery' },
      smokeItems.map((item) =>
        h('div', { class: 'smoke-item', 'data-smoke': item.name, key: item.name },
          h('div', { class: 'smoke-label' }, item.name),
          item.vnode(),
        ),
      ),
    )
}
